#include "sdk_cfg.h"
#include "clock.h"
#include "timer.h"
#include "rtc.h"
#include "key_drv.h"
#include "setup.h"
//#include "key_drv_ad.h"

#include "key_state_scan.h"

#include KEY_MAP_DIR_H


#if defined(ADC_USER_LIBRARY)
#include "adc_api.h"
#endif

static uint8 adc_val[AD_CH_MAX] = {0};

#if defined(_SUPPORT_USB_DET)
static uint16 adc_val_U16[AD_CH_MAX] = {0};
#endif

#if defined(_SPECIAL_PARTY_CONTROL_)
static uint16 adc_party_val[AD_CH_MAX] = {0};
#endif

static uint8 adc_cnt = 0;

static const uint16 ad_conv_table[] =
{
#if defined(ADC_USER_LIBRARY)//--------adc采集使用库函数
#if defined(AD_KEY_KEY1)
    AD_KEY_KEY1,
#endif
#if defined(AD_KEY_KEY2)
	AD_KEY_KEY2,
#endif
#if defined(AD_KEY_ENCODE)
	AD_KEY_ENCODE,
#endif
#if defined(AD_KEY_ENCODE2)
	AD_KEY_ENCODE2,
#endif
#if defined(AD_KEY_ACC)
	AD_KEY_ACC,
#endif
#if defined(_ENABLE_DISC_DETECT_)
#if defined(AD_KEY_DISC)
	AD_KEY_DISC,
#endif
#endif
#if defined(SUPPORT_PARTY_CONTROL)
	AD_KEY_KEY3,
#endif


#else//------------------------------------------

#if defined(AD_KEY_KEY1)
    AD_KEY_KEY1,
#endif
#if defined(AD_KEY_KEY2)
	AD_KEY_KEY2,
#endif
#if defined(AD_KEY_ENCODE)
	AD_KEY_ENCODE,
#endif
#if defined(_SUPPORT_VR2_)
	AD_KEY_ENCODE2,
#endif
#if defined(AD_KEY_ACC)
	AD_KEY_ACC,
#endif
#if defined(_SUPPORT_REAL_VBAR_)
	AD_KEY_VBAR,
#endif
#if defined(SUPPORT_LOW_PWR_DET)
	AD_KEY_BATT_DET,
#endif
#if defined(_ENABLE_DISC_DETECT_)
#if defined(AD_KEY_DISC)
	AD_KEY_DISC,
#endif
#endif
#if defined(SUPPORT_PARTY_CONTROL)||defined(_SL6812_PARTY_CONTROL_)
	AD_KEY_KEY3,
#endif
#if defined(_SUPPORT_USB_DET)
	AD_KEY_USB_DET,
#endif

#if defined(_FY700B_PARTY_CONTROL_)||defined(_XZC1668_ADKEY_CONTROL_)||defined(_KLD3300_PARTY_CONTROL_)||defined(_SUPPORT_SPECIAL_KEY_FUNCTION_)||defined(_YJ3993_ADKEY_CONTROL_)
	AD_KEY_KEY3,
#if !defined(_DISABLE_PARTY_KEY2_)
	AD_KEY_KEY4,
#endif
#endif

#endif
};

static const uint8 ad_ch_table[] =
{
#if defined(ADC_USER_LIBRARY)//--------adc采集使用库函数

#if defined(AD_KEY_KEY1)
    AD_CH_KEY1,
#endif

#if defined(AD_KEY_KEY2)
	AD_CH_KEY2,
#endif

#if defined(AD_KEY_ENCODE)
	AD_CH_ENCODE,
#endif

#if defined(AD_KEY_ENCODE2)
	AD_CH_ENCODE2,
#endif

#if defined(AD_KEY_ACC)
	AD_CH_ACC,
#endif

#if defined(_ENABLE_DISC_DETECT_)
#if defined(AD_KEY_DISC)
	AD_CH_DISC,
#endif
#endif
#if defined(SUPPORT_PARTY_CONTROL)
	AD_CH_KEY3,
#endif

#else//------------------------------------------

#if defined(AD_KEY_ENCODE)
	AD_CH_ENCODE,
#endif
#if defined(_SUPPORT_VR2_)
	AD_CH_ENCODE2,
#endif

#if defined(AD_KEY_KEY1)
    AD_CH_KEY1,
#if defined(AD_KEY_ENCODE)
	AD_CH_ENCODE,
#endif
#if defined(_SUPPORT_VR2_)
	AD_CH_ENCODE2,
#endif
#endif

#if defined(AD_KEY_KEY2)
	AD_CH_KEY2,
#if defined(AD_KEY_ENCODE)
	AD_CH_ENCODE,
#endif
#if defined(_SUPPORT_VR2_)
	AD_CH_ENCODE2,
#endif
#endif

#if defined(AD_KEY_ACC)
	AD_CH_ACC,
#endif

#if defined(_SUPPORT_REAL_VBAR_)
	AD_CH_VBAR,
#endif
#if defined(SUPPORT_LOW_PWR_DET)
	AD_CH_BATT_DET,
#endif

#if defined(_ENABLE_DISC_DETECT_)
#if defined(AD_KEY_DISC)
	AD_CH_DISC,
#endif
#endif
#if defined(SUPPORT_PARTY_CONTROL)||defined(_SL6812_PARTY_CONTROL_)
	AD_CH_KEY3,
#endif
#if defined(_SUPPORT_USB_DET)
	AD_CH_USB_DET,
#endif

#if defined(_FY700B_PARTY_CONTROL_)||defined(_XZC1668_ADKEY_CONTROL_)||defined(_KLD3300_PARTY_CONTROL_)||defined(_SUPPORT_SPECIAL_KEY_FUNCTION_)||defined(_YJ3993_ADKEY_CONTROL_)
	AD_CH_KEY3,
#if !defined(_DISABLE_PARTY_KEY2_)
	AD_CH_KEY4,
#endif
#endif

#endif
};

#define ad_ch_length			sizeof(ad_ch_table)

/*---------------------------------------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------------------------------------*/

typedef struct{
	uint8	KEY_MIN;
	uint8	KEY_MAX;
}KEY_TAB_FORMAT;

#if defined(DTH_USE_KEY1_DETECT)||defined(_USE_KEY2_DETECT)
#define ADC_VALUE_MAX								(57)
#elif defined(_XZC1668_KEY_VALUE_)
#define ADC_VALUE_MAX								(63)
#elif defined(_JYL3391_KEY_VALUE_)
#define ADC_VALUE_MAX								(63)
#else
#define ADC_VALUE_MAX								(62)// 63
#endif
#define ADC_VALUE_MIN								(0)

#define AD_MAX										(ADC_VALUE_MAX)//59
#define ADK_MAX										(AD_MAX - 1)//58
#define ADK_AMP										(4)

#if defined(_SPECIAL_PARTY_CONTROL_)
#define KEY_ADC_VALUE1(x)							(x)
#endif
#define KEY_ADC_VALUE(x)							(x*ADK_AMP)//X*4
#define KEY_ADC_MAX									(KEY_ADC_VALUE(ADK_MAX))//58*4

#define ADC_KEY_TEST_ZERO_VALUE						(KEY_ADC_VALUE(0))//0
#define ADC_KEY_TEST_MAX_VALUE						(KEY_ADC_VALUE(ADK_MAX))//58*4
#define ADC_KEY_MIN(KEY_LOW,KEY)					((uint8)((KEY_LOW+KEY)/2))
#define ADC_KEY_MAX(KEY,KEY_HIGH)					((uint8)(((KEY_HIGH+KEY)/2)-1))


#if defined(GET_KEY1_DATA)
#if defined(ADC1_KEY1_TEST_VALUE)
static const KEY_TAB_FORMAT ADC1_KEY_TAB[]=
{
#if defined(ADC1_KEY1_TEST_VALUE)
	#if defined(ADC1_KEY2_TEST_VALUE)
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC1_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY1_TEST_VALUE,ADC1_KEY2_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC1_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY2_TEST_VALUE)
	#if defined(ADC1_KEY3_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY1_TEST_VALUE,ADC1_KEY2_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY2_TEST_VALUE,ADC1_KEY3_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC1_KEY1_TEST_VALUE,ADC1_KEY2_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY3_TEST_VALUE)
	#if defined(ADC1_KEY4_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY2_TEST_VALUE,ADC1_KEY3_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY3_TEST_VALUE,ADC1_KEY4_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC1_KEY2_TEST_VALUE,ADC1_KEY3_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY3_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY4_TEST_VALUE)
	#if defined(ADC1_KEY5_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY3_TEST_VALUE,ADC1_KEY4_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY4_TEST_VALUE,ADC1_KEY5_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC1_KEY3_TEST_VALUE,ADC1_KEY4_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY5_TEST_VALUE)
	#if defined(ADC1_KEY6_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY4_TEST_VALUE,ADC1_KEY5_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY5_TEST_VALUE,ADC1_KEY6_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC1_KEY4_TEST_VALUE,ADC1_KEY5_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY6_TEST_VALUE)
	#if defined(ADC1_KEY7_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY5_TEST_VALUE,ADC1_KEY6_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY6_TEST_VALUE,ADC1_KEY7_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC1_KEY5_TEST_VALUE,ADC1_KEY6_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY6_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY7_TEST_VALUE)
	#if defined(ADC1_KEY8_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY6_TEST_VALUE,ADC1_KEY7_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY7_TEST_VALUE,ADC1_KEY8_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC1_KEY6_TEST_VALUE,ADC1_KEY7_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY7_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY8_TEST_VALUE)
	#if defined(ADC1_KEY9_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY7_TEST_VALUE,ADC1_KEY8_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY8_TEST_VALUE,ADC1_KEY9_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC1_KEY7_TEST_VALUE,ADC1_KEY8_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY8_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY9_TEST_VALUE)
	#if defined(ADC1_KEY10_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY8_TEST_VALUE,ADC1_KEY9_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY9_TEST_VALUE,ADC1_KEY10_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC1_KEY8_TEST_VALUE,ADC1_KEY9_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY9_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY10_TEST_VALUE)
	#if defined(ADC1_KEY11_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY9_TEST_VALUE,ADC1_KEY10_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY10_TEST_VALUE,ADC1_KEY11_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY9_TEST_VALUE,ADC1_KEY10_TEST_VALUE),		ADC_KEY_MAX(ADC1_KEY10_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY11_TEST_VALUE)
	#if defined(ADC1_KEY12_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY10_TEST_VALUE,ADC1_KEY11_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY11_TEST_VALUE,ADC1_KEY12_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY10_TEST_VALUE,ADC1_KEY11_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY11_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY12_TEST_VALUE)
	#if defined(ADC1_KEY13_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY11_TEST_VALUE,ADC1_KEY12_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY12_TEST_VALUE,ADC1_KEY13_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY11_TEST_VALUE,ADC1_KEY12_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY12_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY13_TEST_VALUE)
	#if defined(ADC1_KEY14_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY12_TEST_VALUE,ADC1_KEY13_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY13_TEST_VALUE,ADC1_KEY14_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY12_TEST_VALUE,ADC1_KEY13_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY13_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY14_TEST_VALUE)
	#if defined(ADC1_KEY15_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY13_TEST_VALUE,ADC1_KEY14_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY14_TEST_VALUE,ADC1_KEY15_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY13_TEST_VALUE,ADC1_KEY14_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY14_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY15_TEST_VALUE)
	#if defined(ADC1_KEY16_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY14_TEST_VALUE,ADC1_KEY15_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY15_TEST_VALUE,ADC1_KEY16_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY14_TEST_VALUE,ADC1_KEY15_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY15_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY16_TEST_VALUE)
	#if defined(ADC1_KEY17_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY15_TEST_VALUE,ADC1_KEY16_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY16_TEST_VALUE,ADC1_KEY17_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY15_TEST_VALUE,ADC1_KEY16_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY16_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY17_TEST_VALUE)
	#if defined(ADC1_KEY18_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY16_TEST_VALUE,ADC1_KEY17_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY17_TEST_VALUE,ADC1_KEY18_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY16_TEST_VALUE,ADC1_KEY17_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY17_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY18_TEST_VALUE)
	#if defined(ADC1_KEY19_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY17_TEST_VALUE,ADC1_KEY18_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY18_TEST_VALUE,ADC1_KEY19_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY17_TEST_VALUE,ADC1_KEY18_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY18_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY19_TEST_VALUE)
	#if defined(ADC1_KEY20_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY18_TEST_VALUE,ADC1_KEY19_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY19_TEST_VALUE,ADC1_KEY20_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY18_TEST_VALUE,ADC1_KEY19_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY19_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY20_TEST_VALUE)
	#if defined(ADC1_KEY21_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY19_TEST_VALUE,ADC1_KEY20_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY20_TEST_VALUE,ADC1_KEY21_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY19_TEST_VALUE,ADC1_KEY20_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY20_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY21_TEST_VALUE)
	#if defined(ADC1_KEY22_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY20_TEST_VALUE,ADC1_KEY21_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY21_TEST_VALUE,ADC1_KEY22_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY20_TEST_VALUE,ADC1_KEY21_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY21_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY22_TEST_VALUE)
	#if defined(ADC1_KEY23_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY21_TEST_VALUE,ADC1_KEY22_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY22_TEST_VALUE,ADC1_KEY23_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY21_TEST_VALUE,ADC1_KEY22_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY22_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY23_TEST_VALUE)
	#if defined(ADC1_KEY24_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY22_TEST_VALUE,ADC1_KEY23_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY23_TEST_VALUE,ADC1_KEY24_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY22_TEST_VALUE,ADC1_KEY23_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY23_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC1_KEY24_TEST_VALUE)
	#if defined(ADC1_KEY25_TEST_VALUE)
	{	ADC_KEY_MIN(ADC1_KEY23_TEST_VALUE,ADC1_KEY24_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY24_TEST_VALUE,ADC1_KEY25_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC1_KEY23_TEST_VALUE,ADC1_KEY24_TEST_VALUE),	ADC_KEY_MAX(ADC1_KEY24_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

};
#endif
#endif

/*---------------------------------------------------------------------------------------------------------------------------------------*/

#if defined(GET_KEY2_DATA)
#if defined(ADC2_KEY1_TEST_VALUE)
static KEY_TAB_FORMAT ADC2_KEY_TAB[]=
{
#if defined(ADC2_KEY1_TEST_VALUE)
	#if defined(ADC2_KEY2_TEST_VALUE)
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC2_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY1_TEST_VALUE,ADC2_KEY2_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC2_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY2_TEST_VALUE)
	#if defined(ADC2_KEY3_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY1_TEST_VALUE,ADC2_KEY2_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY2_TEST_VALUE,ADC2_KEY3_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC2_KEY1_TEST_VALUE,ADC2_KEY2_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY3_TEST_VALUE)
	#if defined(ADC2_KEY4_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY2_TEST_VALUE,ADC2_KEY3_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY3_TEST_VALUE,ADC2_KEY4_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC2_KEY2_TEST_VALUE,ADC2_KEY3_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY3_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY4_TEST_VALUE)
	#if defined(ADC2_KEY5_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY3_TEST_VALUE,ADC2_KEY4_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY4_TEST_VALUE,ADC2_KEY5_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC2_KEY3_TEST_VALUE,ADC2_KEY4_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY5_TEST_VALUE)
	#if defined(ADC2_KEY6_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY4_TEST_VALUE,ADC2_KEY5_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY5_TEST_VALUE,ADC2_KEY6_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC2_KEY4_TEST_VALUE,ADC2_KEY5_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY6_TEST_VALUE)
	#if defined(ADC2_KEY7_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY5_TEST_VALUE,ADC2_KEY6_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY6_TEST_VALUE,ADC2_KEY7_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC2_KEY5_TEST_VALUE,ADC2_KEY6_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY6_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY7_TEST_VALUE)
	#if defined(ADC2_KEY8_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY6_TEST_VALUE,ADC2_KEY7_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY7_TEST_VALUE,ADC2_KEY8_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC2_KEY6_TEST_VALUE,ADC2_KEY7_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY7_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY8_TEST_VALUE)
	#if defined(ADC2_KEY9_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY7_TEST_VALUE,ADC2_KEY8_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY8_TEST_VALUE,ADC2_KEY9_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC2_KEY7_TEST_VALUE,ADC2_KEY8_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY8_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY9_TEST_VALUE)
	#if defined(ADC2_KEY10_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY8_TEST_VALUE,ADC2_KEY9_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY9_TEST_VALUE,ADC2_KEY10_TEST_VALUE)		},
	#else
	{	ADC_KEY_MIN(ADC2_KEY8_TEST_VALUE,ADC2_KEY9_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY9_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY10_TEST_VALUE)
	#if defined(ADC2_KEY11_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY9_TEST_VALUE,ADC2_KEY10_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY10_TEST_VALUE,ADC2_KEY11_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY9_TEST_VALUE,ADC2_KEY10_TEST_VALUE),		ADC_KEY_MAX(ADC2_KEY10_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY11_TEST_VALUE)
	#if defined(ADC2_KEY12_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY10_TEST_VALUE,ADC2_KEY11_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY11_TEST_VALUE,ADC2_KEY12_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY10_TEST_VALUE,ADC2_KEY11_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY11_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY12_TEST_VALUE)
	#if defined(ADC2_KEY13_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY11_TEST_VALUE,ADC2_KEY12_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY12_TEST_VALUE,ADC2_KEY13_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY11_TEST_VALUE,ADC2_KEY12_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY12_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY13_TEST_VALUE)
	#if defined(ADC2_KEY14_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY12_TEST_VALUE,ADC2_KEY13_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY13_TEST_VALUE,ADC2_KEY14_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY12_TEST_VALUE,ADC2_KEY13_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY13_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY14_TEST_VALUE)
	#if defined(ADC2_KEY15_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY13_TEST_VALUE,ADC2_KEY14_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY14_TEST_VALUE,ADC2_KEY15_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY13_TEST_VALUE,ADC2_KEY14_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY14_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY15_TEST_VALUE)
	#if defined(ADC2_KEY16_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY14_TEST_VALUE,ADC2_KEY15_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY15_TEST_VALUE,ADC2_KEY16_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY14_TEST_VALUE,ADC2_KEY15_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY15_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY16_TEST_VALUE)
	#if defined(ADC2_KEY17_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY15_TEST_VALUE,ADC2_KEY16_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY16_TEST_VALUE,ADC2_KEY17_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY15_TEST_VALUE,ADC2_KEY16_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY16_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY17_TEST_VALUE)
	#if defined(ADC2_KEY18_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY16_TEST_VALUE,ADC2_KEY17_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY17_TEST_VALUE,ADC2_KEY18_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY16_TEST_VALUE,ADC2_KEY17_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY17_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY18_TEST_VALUE)
	#if defined(ADC2_KEY19_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY17_TEST_VALUE,ADC2_KEY18_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY18_TEST_VALUE,ADC2_KEY19_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY17_TEST_VALUE,ADC2_KEY18_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY18_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY19_TEST_VALUE)
	#if defined(ADC2_KEY20_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY18_TEST_VALUE,ADC2_KEY19_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY19_TEST_VALUE,ADC2_KEY20_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY18_TEST_VALUE,ADC2_KEY19_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY19_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

#if defined(ADC2_KEY20_TEST_VALUE)
	#if defined(ADC2_KEY21_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY19_TEST_VALUE,ADC2_KEY20_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY20_TEST_VALUE,ADC2_KEY21_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY19_TEST_VALUE,ADC2_KEY20_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY20_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

#if defined(ADC2_KEY21_TEST_VALUE)
	#if defined(ADC2_KEY22_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY20_TEST_VALUE,ADC2_KEY21_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY21_TEST_VALUE,ADC2_KEY22_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY20_TEST_VALUE,ADC2_KEY21_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY21_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY22_TEST_VALUE)
	#if defined(ADC2_KEY23_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY21_TEST_VALUE,ADC2_KEY22_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY22_TEST_VALUE,ADC2_KEY23_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY21_TEST_VALUE,ADC2_KEY22_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY22_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY23_TEST_VALUE)
	#if defined(ADC2_KEY24_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY22_TEST_VALUE,ADC2_KEY23_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY23_TEST_VALUE,ADC2_KEY24_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY22_TEST_VALUE,ADC2_KEY23_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY23_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC2_KEY24_TEST_VALUE)
	#if defined(ADC2_KEY25_TEST_VALUE)
	{	ADC_KEY_MIN(ADC2_KEY23_TEST_VALUE,ADC2_KEY24_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY24_TEST_VALUE,ADC2_KEY25_TEST_VALUE)	},
	#else
	{	ADC_KEY_MIN(ADC2_KEY23_TEST_VALUE,ADC2_KEY24_TEST_VALUE),	ADC_KEY_MAX(ADC2_KEY24_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

};
#endif
#endif

/*---------------------------------------------------------------------------------------------------------------------------------------*/
#if defined(SUPPORT_PARTY_CONTROL)||defined(_SUPPORT_SPECIAL_KEY_FUNCTION_)||defined(_SL6812_PARTY_CONTROL_)
#if !defined(_SPECIAL_PARTY_CONTROL_)
static KEY_TAB_FORMAT ADC3_KEY_TAB[]=
 {
#if defined(ADC3_KEY1_TEST_VALUE)
	#if defined(ADC3_KEY2_TEST_VALUE)
		{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY2_TEST_VALUE)
	#if defined(ADC3_KEY3_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY3_TEST_VALUE)
	#if defined(ADC3_KEY4_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY4_TEST_VALUE)
	#if defined(ADC3_KEY5_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY5_TEST_VALUE)
	#if defined(ADC3_KEY6_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY6_TEST_VALUE)
	#if defined(ADC3_KEY7_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY6_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY7_TEST_VALUE)
	#if defined(ADC3_KEY8_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY7_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY8_TEST_VALUE)
	#if defined(ADC3_KEY9_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY8_TEST_VALUE,ADC3_KEY9_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY8_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY9_TEST_VALUE)
	#if defined(ADC3_KEY10_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY8_TEST_VALUE,ADC3_KEY9_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY9_TEST_VALUE,ADC3_KEY10_TEST_VALUE) 	},
	#else
		{	ADC_KEY_MIN(ADC3_KEY8_TEST_VALUE,ADC3_KEY9_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY9_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY10_TEST_VALUE)
	#if defined(ADC3_KEY11_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY9_TEST_VALUE,ADC3_KEY10_TEST_VALUE),		ADC_KEY_MAX(ADC3_KEY10_TEST_VALUE,ADC3_KEY11_TEST_VALUE)	},
	#else
		{	ADC_KEY_MIN(ADC3_KEY9_TEST_VALUE,ADC3_KEY10_TEST_VALUE),		ADC_KEY_MAX(ADC3_KEY10_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

#if defined(ADC3_KEY11_TEST_VALUE)
	#if defined(ADC3_KEY12_TEST_VALUE)
			{	ADC_KEY_MIN(ADC3_KEY10_TEST_VALUE,ADC3_KEY11_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY11_TEST_VALUE,ADC3_KEY12_TEST_VALUE)	},
	#else
			{	ADC_KEY_MIN(ADC3_KEY10_TEST_VALUE,ADC3_KEY11_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY11_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

#if defined(ADC3_KEY12_TEST_VALUE)
	#if defined(ADC3_KEY13_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY11_TEST_VALUE,ADC3_KEY12_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY12_TEST_VALUE,ADC3_KEY13_TEST_VALUE)	},
	#else
		{	ADC_KEY_MIN(ADC3_KEY11_TEST_VALUE,ADC3_KEY12_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY12_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY13_TEST_VALUE)
	#if defined(ADC3_KEY14_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY12_TEST_VALUE,ADC3_KEY13_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY13_TEST_VALUE,ADC3_KEY14_TEST_VALUE)	},
	#else
		{	ADC_KEY_MIN(ADC3_KEY12_TEST_VALUE,ADC3_KEY13_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY13_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY14_TEST_VALUE)
	#if defined(ADC3_KEY15_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY13_TEST_VALUE,ADC3_KEY14_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY14_TEST_VALUE,ADC3_KEY15_TEST_VALUE)	},
	#else
		{	ADC_KEY_MIN(ADC3_KEY13_TEST_VALUE,ADC3_KEY14_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY14_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY15_TEST_VALUE)
	#if defined(ADC3_KEY16_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY14_TEST_VALUE,ADC3_KEY15_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY15_TEST_VALUE,ADC3_KEY16_TEST_VALUE)	},
	#else
		{	ADC_KEY_MIN(ADC3_KEY14_TEST_VALUE,ADC3_KEY15_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY15_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

#if defined(ADC2_KEY16_TEST_VALUE)
	#if defined(ADC3_KEY17_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY15_TEST_VALUE,ADC3_KEY16_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY16_TEST_VALUE,ADC3_KEY17_TEST_VALUE)	},
	#else
		{	ADC_KEY_MIN(ADC3_KEY15_TEST_VALUE,ADC3_KEY16_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY16_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif
};
#endif
#endif

#if defined(_SPECIAL_PARTY_CONTROL_)
static KEY_TAB_FORMAT ADC3_KEY_TAB[]=
{
#if defined(ADC3_KEY1_TEST_VALUE)
	#if defined(ADC3_KEY2_TEST_VALUE)
		{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,255)	},
	#endif
#endif


#if defined(ADC3_KEY2_TEST_VALUE)
	#if defined(ADC3_KEY3_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,255)	},
	#endif
#endif


#if defined(ADC3_KEY3_TEST_VALUE)
	#if defined(ADC3_KEY4_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,255)	},
	#endif
#endif


#if defined(ADC3_KEY4_TEST_VALUE)
	#if defined(ADC3_KEY5_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,255)	},
	#endif
#endif


#if defined(ADC3_KEY5_TEST_VALUE)
	#if defined(ADC3_KEY6_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,255)	},
	#endif
#endif


#if defined(ADC3_KEY6_TEST_VALUE)
	#if defined(ADC3_KEY7_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY6_TEST_VALUE,255)	},
	#endif
#endif


#if defined(ADC3_KEY7_TEST_VALUE)
	#if defined(ADC3_KEY8_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY7_TEST_VALUE,255)	},
	#endif
#endif


#if defined(ADC3_KEY8_TEST_VALUE)
	#if defined(ADC3_KEY9_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY8_TEST_VALUE,ADC3_KEY9_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY8_TEST_VALUE,255)	},
	#endif
#endif
};
#endif

#if defined(_FY700B_PARTY_CONTROL_)&&0
static KEY_TAB_FORMAT ADC3_KEY_TAB[]=
 {
#if defined(ADC3_KEY1_TEST_VALUE)
	#if defined(ADC3_KEY2_TEST_VALUE)
		{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY2_TEST_VALUE)
	#if defined(ADC3_KEY3_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY3_TEST_VALUE)
	#if defined(ADC3_KEY4_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY4_TEST_VALUE)
	#if defined(ADC3_KEY5_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY5_TEST_VALUE)
	#if defined(ADC3_KEY6_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY6_TEST_VALUE)
	#if defined(ADC3_KEY7_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY6_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY7_TEST_VALUE)
	#if defined(ADC3_KEY8_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY7_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC3_KEY8_TEST_VALUE)
	#if defined(ADC3_KEY9_TEST_VALUE)
		{	ADC_KEY_MIN(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY8_TEST_VALUE,ADC3_KEY9_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC3_KEY7_TEST_VALUE,ADC3_KEY8_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY8_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

};
#endif


#if defined(_FY700B_PARTY_CONTROL_)||defined(_SUPPORT_SPECIAL_KEY_FUNCTION_)
static KEY_TAB_FORMAT ADC4_KEY_TAB[]=
 {
#if defined(ADC4_KEY1_TEST_VALUE)
	#if defined(ADC4_KEY2_TEST_VALUE)
		{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC4_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC4_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC4_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY2_TEST_VALUE)
	#if defined(ADC4_KEY3_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY3_TEST_VALUE)
	#if defined(ADC4_KEY4_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC4_KEY4_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY4_TEST_VALUE)
	#if defined(ADC4_KEY5_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY3_TEST_VALUE,ADC4_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC4_KEY3_TEST_VALUE,ADC4_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY5_TEST_VALUE)
	#if defined(ADC4_KEY6_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY4_TEST_VALUE,ADC4_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY5_TEST_VALUE,ADC4_KEY6_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC4_KEY4_TEST_VALUE,ADC4_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY6_TEST_VALUE)
	#if defined(ADC4_KEY7_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY5_TEST_VALUE,ADC4_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY6_TEST_VALUE,ADC4_KEY7_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC4_KEY5_TEST_VALUE,ADC4_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY6_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY7_TEST_VALUE)
	#if defined(ADC4_KEY8_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY6_TEST_VALUE,ADC4_KEY7_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY7_TEST_VALUE,ADC4_KEY8_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC4_KEY6_TEST_VALUE,ADC4_KEY7_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY7_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY8_TEST_VALUE)
	#if defined(ADC4_KEY9_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY7_TEST_VALUE,ADC4_KEY8_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY8_TEST_VALUE,ADC4_KEY9_TEST_VALUE)		},
	#else
		{	ADC_KEY_MIN(ADC4_KEY7_TEST_VALUE,ADC4_KEY8_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY8_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY9_TEST_VALUE)
	#if defined(ADC4_KEY10_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY8_TEST_VALUE,ADC4_KEY9_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY9_TEST_VALUE,ADC4_KEY10_TEST_VALUE) 	},
	#else
		{	ADC_KEY_MIN(ADC4_KEY8_TEST_VALUE,ADC4_KEY9_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY9_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif


#if defined(ADC4_KEY10_TEST_VALUE)
	#if defined(ADC4_KEY11_TEST_VALUE)
		{	ADC_KEY_MIN(ADC4_KEY9_TEST_VALUE,ADC4_KEY10_TEST_VALUE),		ADC_KEY_MAX(ADC4_KEY10_TEST_VALUE,ADC4_KEY11_TEST_VALUE)	},
	#else
		{	ADC_KEY_MIN(ADC4_KEY9_TEST_VALUE,ADC4_KEY10_TEST_VALUE),		ADC_KEY_MAX(ADC4_KEY10_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif

#if defined(ADC4_KEY11_TEST_VALUE)
	#if defined(ADC4_KEY12_TEST_VALUE)
			{	ADC_KEY_MIN(ADC4_KEY10_TEST_VALUE,ADC3_KEY11_TEST_VALUE),	ADC_KEY_MAX(ADC4_KEY11_TEST_VALUE,ADC4_KEY12_TEST_VALUE)	},
	#else
			{	ADC_KEY_MIN(ADC4_KEY10_TEST_VALUE,ADC3_KEY11_TEST_VALUE),	ADC_KEY_MAX(ADC4_KEY11_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
	#endif
#endif
};
#endif

#if defined(_XZC1668_ADKEY_CONTROL_)||defined(_YJ3993_ADKEY_CONTROL_)
static KEY_TAB_FORMAT ADC3_KEY_TAB[]=
{
#if defined(ADC3_KEY1_TEST_VALUE)
#if defined(ADC3_KEY2_TEST_VALUE)
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY2_TEST_VALUE)
#if defined(ADC3_KEY3_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY3_TEST_VALUE)
#if defined(ADC3_KEY4_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY4_TEST_VALUE)
#if defined(ADC3_KEY5_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY5_TEST_VALUE)
#if defined(ADC3_KEY6_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY6_TEST_VALUE)
#if defined(ADC3_KEY7_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY6_TEST_VALUE,ADC3_KEY7_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY6_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif
};

static KEY_TAB_FORMAT ADC4_KEY_TAB[]=
{
#if defined(ADC4_KEY1_TEST_VALUE)
#if defined(ADC4_KEY2_TEST_VALUE)
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC4_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC4_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC4_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif


#if defined(ADC4_KEY2_TEST_VALUE)
#if defined(ADC4_KEY3_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif


#if defined(ADC4_KEY3_TEST_VALUE)
#if defined(ADC4_KEY4_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC4_KEY4_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif


#if defined(ADC4_KEY4_TEST_VALUE)
#if defined(ADC4_KEY5_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY3_TEST_VALUE,ADC4_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC4_KEY5_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY3_TEST_VALUE,ADC4_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif


#if defined(ADC4_KEY5_TEST_VALUE)
#if defined(ADC4_KEY6_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY4_TEST_VALUE,ADC4_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY5_TEST_VALUE,ADC4_KEY6_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY4_TEST_VALUE,ADC4_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC4_KEY6_TEST_VALUE)
#if defined(ADC4_KEY7_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY4_TEST_VALUE,ADC4_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY6_TEST_VALUE,ADC4_KEY7_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY4_TEST_VALUE,ADC4_KEY6_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY6_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

};
#endif

#if defined(_KLD3300_PARTY_CONTROL_)
static KEY_TAB_FORMAT ADC3_KEY_TAB[]=
{
#if defined(ADC3_KEY1_TEST_VALUE)
#if defined(ADC3_KEY2_TEST_VALUE)
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC3_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC3_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY2_TEST_VALUE)
#if defined(ADC3_KEY3_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY1_TEST_VALUE,ADC3_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY3_TEST_VALUE)
#if defined(ADC3_KEY4_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY2_TEST_VALUE,ADC3_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY3_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY4_TEST_VALUE)
#if defined(ADC3_KEY5_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY3_TEST_VALUE,ADC3_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif

#if defined(ADC3_KEY5_TEST_VALUE)
#if defined(ADC3_KEY6_TEST_VALUE)
	{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC3_KEY6_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC3_KEY4_TEST_VALUE,ADC3_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC3_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif
};

static KEY_TAB_FORMAT ADC4_KEY_TAB[]=
{
#if defined(ADC4_KEY1_TEST_VALUE)
#if defined(ADC4_KEY2_TEST_VALUE)
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC4_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC_KEY_TEST_ZERO_VALUE,ADC4_KEY1_TEST_VALUE),	ADC_KEY_MAX(ADC4_KEY1_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif


#if defined(ADC4_KEY2_TEST_VALUE)
#if defined(ADC4_KEY3_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY1_TEST_VALUE,ADC4_KEY2_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY2_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif


#if defined(ADC4_KEY3_TEST_VALUE)
#if defined(ADC4_KEY4_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC4_KEY4_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY2_TEST_VALUE,ADC4_KEY3_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif


#if defined(ADC4_KEY4_TEST_VALUE)
#if defined(ADC4_KEY5_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY3_TEST_VALUE,ADC4_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC4_KEY5_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY3_TEST_VALUE,ADC4_KEY4_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY4_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif


#if defined(ADC4_KEY5_TEST_VALUE)
#if defined(ADC4_KEY6_TEST_VALUE)
	{	ADC_KEY_MIN(ADC4_KEY4_TEST_VALUE,ADC4_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY5_TEST_VALUE,ADC4_KEY6_TEST_VALUE)		},
#else
	{	ADC_KEY_MIN(ADC4_KEY4_TEST_VALUE,ADC4_KEY5_TEST_VALUE), 	ADC_KEY_MAX(ADC4_KEY5_TEST_VALUE,ADC_KEY_TEST_MAX_VALUE)	},
#endif
#endif
};
#endif

#if defined(GET_KEY1_DATA)
#define ADC_KEY1_TAB_SIZE								(sizeof(ADC1_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#endif
#if defined(GET_KEY2_DATA)
#define ADC_KEY2_TAB_SIZE								(sizeof(ADC2_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#endif
#if defined(SUPPORT_PARTY_CONTROL)||defined(_SL6812_PARTY_CONTROL_)
#define ADC_KEY3_TAB_SIZE								(sizeof(ADC3_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#endif
#if defined(_FY700B_PARTY_CONTROL_)
//#define ADC_KEY3_TAB_SIZE								(sizeof(ADC3_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#define ADC_KEY4_TAB_SIZE								(sizeof(ADC4_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#endif

#if defined(_XZC1668_ADKEY_CONTROL_)||defined(_SUPPORT_SPECIAL_KEY_FUNCTION_)||defined(_YJ3993_ADKEY_CONTROL_)
#define ADC_KEY3_TAB_SIZE								(sizeof(ADC3_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#define ADC_KEY4_TAB_SIZE								(sizeof(ADC4_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#endif

#if defined(_KLD3300_PARTY_CONTROL_)
#define ADC_KEY3_TAB_SIZE								(sizeof(ADC3_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#define ADC_KEY4_TAB_SIZE								(sizeof(ADC4_KEY_TAB)/sizeof(KEY_TAB_FORMAT))
#endif

/*---------------------------------------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------------------------------------*/

static const u32 sys2adc_clk_info[] =
{
    128000000L,
    96000000L,
    72000000L,
    48000000L,
    24000000L,
    12000000L,
    6000000L,
    1000000L,
};

static void set_adc_clk(void)
{
    u32 adc_clk;
    u32 i;
    u8 cnt;

    //ADC 时钟配置
    adc_clk = clock_get_lsb_freq();
    cnt = sizeof(sys2adc_clk_info)/sizeof(sys2adc_clk_info[0]);
    for(i = 0;i< cnt;i++ )
    {
        if( adc_clk > sys2adc_clk_info[i])
        {
            break;
        }
    }

    if(i < cnt)
    {
        i = cnt -i;
    }
    else
    {
        i = cnt -1;
    }

    key_printf("ADC_DIV = %d\n",i);
    JL_ADC->CON &= ~(BIT(2) | BIT(1) | BIT(0));
    JL_ADC->CON |= (i & 0x7L );
}

#if defined(_ENABLE_CHANNEL_DISTURB_)
extern u16 adc_res_api(u32 channel);
#endif
static void adc_scan(void *param)
{
#if defined(ADC_USER_LIBRARY)
	for(u8 i=0;i<ad_ch_length;i++)
	{
		adc_ch_sel(ad_conv_table[i]);
		adc_val[i] =((adc_res_api(ad_conv_table[i]) >> 4)&0x3F);
	}
#elif defined(_ENABLE_CHANNEL_DISTURB_)
    static u8 next_channel = 0;
    next_channel = adc_cnt + 1;
    if(next_channel == ad_ch_length)
    		next_channel = 0;

    uint8 ch = ad_ch_table[adc_cnt++];
    uint8 ch1 = ad_ch_table[next_channel];
    adc_val[ch] = (adc_res_api(ad_conv_table[ch1])>> 4) & 0x3F;

    if (adc_cnt == ad_ch_length)
    		adc_cnt = 0;
#else
    if(BIT(7) & JL_ADC->CON)
	{
		uint8 ch = ad_ch_table[adc_cnt];

	    adc_val[ch] = ((JL_ADC->RES >> 4) & 0x3F);

	#if defined(_SUPPORT_USB_DET)
		adc_val_U16[ch] = (JL_ADC->RES );
	#endif

	#if defined(_SPECIAL_PARTY_CONTROL_)
		adc_party_val[ch] = (JL_ADC->RES );
	#endif

	    if((++adc_cnt) >= ad_ch_length)
	    {
	        adc_cnt = 0;
	    }

		ch = ad_ch_table[adc_cnt];

	    JL_ADC->CON &= ~0x0f00;         		//AD口clear
	    JL_ADC->CON |= ad_conv_table[ch];  		//AD口选择
	    JL_ADC->CON |= BIT(6);             		//启动ADC
    }
#endif
}

void ad_key_init(void)
{

    key_puts("ad key init\n");

	adc_cnt = 0;

	uint8 i;
	for(i = 0; i < sizeof(ad_conv_table)/sizeof(ad_conv_table[0]); i++)
	{
	#define PORTA_AD_INIT(x)		do{JL_PORTA->PD &= ~BIT(x); JL_PORTA->PU &= ~BIT(x); JL_PORTA->DIR |= BIT(x); JL_PORTA->DIE &= ~BIT(x);}while(0)
	#define PORTB_AD_INIT(x)		do{JL_PORTB->PD &= ~BIT(x); JL_PORTB->PU &= ~BIT(x); JL_PORTB->DIR |= BIT(x); JL_PORTB->DIE &= ~BIT(x);}while(0)
	#define PORTR_AD_INIT(x)		do{PORTR_PU(PORTR##x,0); PORTR_PD(PORTR##x,0); PORTR_DIR(PORTR##x,1); PORTR_DIE(PORTR##x,1); }while(0)
		switch(ad_conv_table[i])
		{
			case AD_KEY_PA3:	PORTA_AD_INIT(3);	break;
			case AD_KEY_PA4:	PORTA_AD_INIT(4);	break;
			case AD_KEY_PA5:	PORTA_AD_INIT(5);	break;
			case AD_KEY_PA6:	PORTA_AD_INIT(6);	break;
			case AD_KEY_PA9:	PORTA_AD_INIT(9);	break;
			case AD_KEY_PA10:	PORTA_AD_INIT(10);	break;

			case AD_KEY_PB7:	PORTB_AD_INIT(7);	break;
			case AD_KEY_PB8:	PORTB_AD_INIT(8);	break;
			case AD_KEY_PB9:	PORTB_AD_INIT(9);	break;
			case AD_KEY_PB10:	PORTB_AD_INIT(10);	break;
			case AD_KEY_PB11:	PORTB_AD_INIT(11);	break;
			case AD_KEY_PB12:	PORTB_AD_INIT(12);	break;

			case AD_KEY_PR1:	PORTR_AD_INIT(1);	PORTR1_ADCEN_CTL(1); break;
			case AD_KEY_PR2:	PORTR_AD_INIT(2);	PORTR2_ADCEN_CTL(1); break;

			default:
				break;
		}
	}
#if defined(ADC_USER_LIBRARY)
	for(i = 0; i < sizeof(ad_conv_table)/sizeof(ad_conv_table[0]); i++)
	{
		adc_init_api(ad_conv_table[i],clock_get_lsb_freq(),SYS_LVD_EN);
	}
#else
    JL_ADC->CON = 0;

    set_adc_clk();           			//设置时钟

    JL_ADC->CON |= (0XF<<12);    							//启动延时控制
    JL_ADC->CON |= ad_conv_table[ad_ch_table[adc_cnt]];  	//AD口选择
    JL_ADC->CON |= BIT(3);       							//ADC模拟模块使能
    JL_ADC->CON |= BIT(4);       							//ADC控制器使能
    JL_ADC->CON |= BIT(6);       							//启动ADC
#endif

#if defined(_SPECIAL_DRIVER_ADC_)
	ADC_KEY1_INIT();ADC_KEY1_IN();ADC_KEY1_LOW();
	ADC_KEY2_INIT();ADC_KEY2_IN();ADC_KEY2_LOW();
	ADC_KEY3_INIT();ADC_KEY3_IN();ADC_KEY3_LOW();
	ADC_KEY4_INIT();ADC_KEY4_IN();ADC_KEY4_LOW();
#endif

#if defined(_ENABLE_RADIO_TIME_)
	timer_reg_func(adc_scan, NULL, 4);
#else
	timer_reg_func(adc_scan, NULL, 2);
#endif
}

uint8 adc_value(uint8 ch)
{
	if(ch < AD_CH_MAX)
	{
		return adc_val[ch];
		//key_printf("GET_DISC_DATA22222222222222222222222=%d\n", GET_DISC_DATA);
	}
	return 0;
}

#if defined(_SUPPORT_USB_DET)
uint16 adc_value_u16(uint8 ch)
{
	if(ch < AD_CH_MAX)
	{
		return adc_val_U16[ch];
	}
	return 0;
}
#endif

#if defined(_SPECIAL_PARTY_CONTROL_)
uint16 adc_value_party(uint8 ch)
{
	if(ch < AD_CH_MAX)
	{
		return adc_party_val[ch];
	}
	return 0;
}
#endif

#if defined(_SUPPORT_TOUCH_KEY_)&&0
extern uint8 Read_Touch_Value(uint8 Reg);
uint8 touch_key_scan(void)
{
	uint8  TouchValueA,TouchValueB;
	uint16 TouchValueC;

	if(setup.touch_init)
	{
		TouchValueA = Read_Touch_Value(0x34);
		TouchValueB = Read_Touch_Value(0x35);

		TouchValueC = TouchValueB*256+TouchValueA;

		if(TouchValueC != 0)
		{
			//ew_printf("TouchValueA:0x%x\n", TouchValueA);
			//ew_printf("TouchValueB:0x%x\n", TouchValueB);
			//ew_printf("TouchValueC:0x%x\n", TouchValueC);
		}

	#if defined(_XM007_SPECIAL_BACKLIGHT_)
		if(!global.sys_power)
		{
			if((TouchValueC == 0x01)||(TouchValueC == 0x02)||(TouchValueC == 0x04)||(TouchValueC == 0x08)||(TouchValueC == 0x10)
			||(TouchValueC == 0x20)||(TouchValueC == 0x40)||(TouchValueC == 0x80)||(TouchValueC == 0x100)||(TouchValueC == 0x200)
			||(TouchValueC == 0x400)||(TouchValueC == 0x800)||(TouchValueC == 0x1000)||(TouchValueC == 0x2000)||(TouchValueC == 0x4000))
			{
				global.off_flag = TRUE;
				global.off_time = 100;
			}
		}
	#endif

		switch(TouchValueC)
		{
			case 0x01:
				return 2;
				break;
			case 0x02:
				return 3;
				break;
			case 0x04:
				return 4;
				break;
			case 0x08:
				return 5;
				break;
			case 0x10:
				return 6;
				break;
			case 0x20:
				return 7;
				break;
			case 0x40:
				return 8;
				break;
			case 0x80:
				return 9;
				break;
			case 0x100:
				return 10;
				break;
			case 0x200:
				return 11;
				break;
			case 0x400:
				return 12;
				break;
			case 0x800:
				return 13;
				break;
			case 0x1000:
				return 14;
				break;
			case 0x2000:
				return 15;
				break;
			case 0x4000:
				return 16;
				break;
		}
		return KEY_VALUE_NULL;
	}
	return KEY_VALUE_NULL;
}
#endif

#if defined(_SPECIAL_DRIVER_ADC_)
static void ad_key_delay(void)
{
	int i;
	for(i = 0; i < 30; i++)
	{
		asm volatile ("nop");
	}
}

uint8 ad_key_scan(void)
{
#if defined(_ENABLE_VR_KEY_)
	if(GET_ENCODE_DATA < 3)
	{
		return 1;
	}
	else
#endif
	{
    	if(!ADC_KEY1_GET())
    	{
    		//key_puts("key1\n");
    		return 2;
    	}
    	else if(!ADC_KEY2_GET())
    	{
    		//key_puts("key2\n");
    		return 3;
    	}
    	else if(!ADC_KEY3_GET())
    	{
    		//key_puts("key3\n");
    		return 4;
    	}
    	else if(!ADC_KEY4_GET())
    	{
    		//key_puts("key4\n");
    		return 5;
    	}

    //---------Detect KEY1
    	ADC_KEY1_OUT();
    	ad_key_delay();
    	if(!ADC_KEY2_GET())
    	{
    		ADC_KEY1_IN();
    		//key_puts("key5\n");
    		return 6;
    	}
    	else if(!ADC_KEY3_GET())
    	{
    		ADC_KEY1_IN();
    		//key_puts("key6\n");
    		return 7;
    	}
    	else if(!ADC_KEY4_GET())
    	{
    		ADC_KEY1_IN();
    		//key_puts("key7\n");
    		return 8;
    	}
    	ADC_KEY1_IN();

    //---------Detect KEY2
    	ADC_KEY2_OUT();
    	ad_key_delay();
    	if(!ADC_KEY1_GET())
    	{
    		ADC_KEY2_IN();
    		//key_puts("key8\n");
    		return 9;
    	}
    	else if(!ADC_KEY3_GET())
    	{
    		ADC_KEY2_IN();
    		//key_puts("key9\n");
    		return 10;
    	}
    	else if(!ADC_KEY4_GET())
    	{
    		ADC_KEY2_IN();
    		//key_puts("key10\n");
    		return 11;
    	}
    	ADC_KEY2_IN();

    //---------Detect KEY3
    	ADC_KEY3_OUT();
    	ad_key_delay();
    	if(!ADC_KEY1_GET())
    	{
    		ADC_KEY3_IN();
    		//key_puts("key11\n");
    		return 12;
    	}
    	else if(!ADC_KEY2_GET())
    	{
    		ADC_KEY3_IN();
    		//key_puts("key12\n");
    		return 13;
    	}
    	else if(!ADC_KEY4_GET())
    	{
    		ADC_KEY3_IN();
    		//key_puts("key13\n");
    		return 14;
    	}
    	ADC_KEY3_IN();

    //---------Detect KEY4
    	ADC_KEY4_OUT();
    	ad_key_delay();
    	if(!ADC_KEY1_GET())
    	{
    		ADC_KEY4_IN();
    		//key_puts("key14\n");
    		return 15;
    	}
    	else if(!ADC_KEY2_GET())
    	{
    		ADC_KEY4_IN();
    		//key_puts("key15\n");
    		return 16;
    	}
    	else if(!ADC_KEY3_GET())
    	{
    		ADC_KEY4_IN();
    		//key_puts("key16\n");
    		return 17;
    	}
    	ADC_KEY4_IN();

    	return KEY_VALUE_NULL;
	}
}

#elif defined(_SUPPORT_SPECIAL_KEY_FUNCTION_)
uint8 ad_key_scan(void)
{
    uint8 i;
 	uint8 key;

	key = GET_KEY1_DATA;
	key *= ADK_AMP;

	if(key < KEY_ADC_MAX)
	{
	  if(!setup.ad_keyflag)
	  {
      #if defined(ADC1_KEY1_TEST_VALUE)
	    for(i = 0; i < ADC_KEY1_TAB_SIZE; i++)
	    {
		   if((key >= ADC1_KEY_TAB[i].KEY_MIN) && (key <= ADC1_KEY_TAB[i].KEY_MAX))break;
	    }
	    if(i==ADC_KEY1_TAB_SIZE)return KEY_VALUE_NULL;
	    else
	    {
		   //key_printf("ad_key1_scan=%d, id:%d\n", GET_KEY1_DATA, (i+1));
		   return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE);
	    }
      #endif
	  }
	  else
	  {
      #if defined(ADC1_KEY1_TEST_VALUE)
    	for(i = 0; i < ADC_KEY1_TAB_SIZE; i++)
    	{
    		if((key >= ADC1_KEY_TAB[i].KEY_MIN) && (key <= ADC1_KEY_TAB[i].KEY_MAX))break;
    	}
    	if(i==ADC_KEY1_TAB_SIZE)return KEY_VALUE_NULL;
    	else
    	{
    		//key_printf("ad_key1_scan=%d, id:%d\n", GET_KEY1_DATA, (i+1));
    		return (i+1);
    	}
      #endif
	  }
	}

	key = GET_KEY2_DATA;
	key *= ADK_AMP;

	if(key < KEY_ADC_MAX)
	{
	 if(!setup.ad_keyflag)
	 {
      #if defined(ADC2_KEY1_TEST_VALUE)
		for(i=0;i<ADC_KEY2_TAB_SIZE;i++)
		{
			if((key >= ADC2_KEY_TAB[i].KEY_MIN) && (key <= ADC2_KEY_TAB[i].KEY_MAX))break;
		}
		if(i==ADC_KEY2_TAB_SIZE)return KEY_VALUE_NULL;
		else
	    {
    	#if defined(ADC1_KEY1_TEST_VALUE)
		    //key_printf("ad_key2_scan=%d, id:%d\n", GET_KEY2_DATA, (i+1+ADC_KEY1_TAB_SIZE));
			return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE+9);
    	#endif
		}
      #endif
	 }
	 else
	 {
	 #if defined(ADC2_KEY1_TEST_VALUE)
		for(i=0;i<ADC_KEY2_TAB_SIZE;i++)
		{
			if((key >= ADC2_KEY_TAB[i].KEY_MIN) && (key <= ADC2_KEY_TAB[i].KEY_MAX))break;
		}
		if(i==ADC_KEY2_TAB_SIZE)return KEY_VALUE_NULL;
		else
		{
		#if defined(ADC1_KEY1_TEST_VALUE)
		    //key_printf("ad_key2_scan=%d, id:%d\n", GET_KEY2_DATA, (i+1+ADC_KEY1_TAB_SIZE));
			return (i+1+ADC_KEY1_TAB_SIZE);
		#endif
		}
	 #endif
	 }
   }

     return KEY_VALUE_NULL;
}

#elif defined(_SL6812_KEY_FUNTION_)

#if defined(_SL6812_KEY_FUNTION_)
uint32 key_down_time=0;
#endif
#if defined(_SL6812_TEST_LCD_)
uint8 key_up_flag=0;
uint32 key_up_time=0;
#endif
uint8 ad_key_scan(void)
{
	uint8 i;
	uint8 key;

#if defined(GET_KEY1_DATA)

	key = GET_KEY1_DATA;
	key *= ADK_AMP;

	if(key < KEY_ADC_MAX)
	{
	#if defined(ADC1_KEY1_TEST_VALUE)
		for(i = 0; i < ADC_KEY1_TAB_SIZE; i++)
		{
			if((key >= ADC1_KEY_TAB[i].KEY_MIN) && (key <= ADC1_KEY_TAB[i].KEY_MAX))break;
		}
		if(i==ADC_KEY1_TAB_SIZE)return KEY_VALUE_NULL;
		else
		{
			//key_printf("ad_key1_scan=%d, id:%d\n", GET_KEY1_DATA, (i+1));
		#if defined(_SL6812_KEY_FUNTION_)
			if(((GET_KEY1_DATA > 4)&&(GET_KEY1_DATA < 11)) && ((GET_KEY2_DATA > 20)&&(GET_KEY2_DATA < 25)))
			{
				key_down_time++;
				if(key_down_time < 5)
				{
					return 0;
				}
				else
				{
					return 19;
				}
			}
		#if defined(_ENABLE_PWD_RESET_)
			else if(((GET_KEY1_DATA > 19)&&(GET_KEY1_DATA < 25)) && ((GET_KEY2_DATA > 8)&&(GET_KEY2_DATA < 14)))
			{
				key_down_time++;
				if(key_down_time < 5)
				{
					return 0;
				}
				else
				{
					return 20;
				}
			}
		#endif
			else
			{
				return (i+1);
			}
		#else
			return (i+1);
		#endif
		}
	#endif
	}
#endif

#if defined( GET_KEY2_DATA )
	key = GET_KEY2_DATA;
	key *= ADK_AMP;
	//key_printf("22ad_key2_scan=%d\n", GET_KEY2_DATA);
	if(key < KEY_ADC_MAX)
	{
	#if defined(ADC2_KEY1_TEST_VALUE)
		for(i=0;i<ADC_KEY2_TAB_SIZE;i++)
		{
			if((key >= ADC2_KEY_TAB[i].KEY_MIN) && (key <= ADC2_KEY_TAB[i].KEY_MAX))break;
		}
		if(i==ADC_KEY2_TAB_SIZE)return KEY_VALUE_NULL;
		else
		{
		#if defined(ADC1_KEY1_TEST_VALUE)
			//key_printf("ad_key2_scan=%d, id:%d\n", GET_KEY2_DATA, (i+1+ADC_KEY1_TAB_SIZE));

		#if defined(_SL6812_TEST_LCD_)
			if(((GET_KEY2_DATA >24)&&(GET_KEY2_DATA < 30)) || ((GET_KEY2_DATA > 20)&&(GET_KEY2_DATA < 25)) || ((GET_KEY2_DATA > 41)&&(GET_KEY2_DATA < 47)))
			{
				key_up_flag = TRUE;
			}
			if(key_up_flag)
			{
				if(((GET_KEY2_DATA > 12)&&(GET_KEY2_DATA < 18)) || ((GET_KEY2_DATA > 17)&&(GET_KEY2_DATA < 21)))
				{
					key_up_time++;
					if(key_up_time < 5)
					{
						return 0;
					}
					else
					{
						return (i+1+ADC_KEY1_TAB_SIZE);
					}
				}
				else
				{
					return (i+1+ADC_KEY1_TAB_SIZE);
				}
			}
			else
			{
				return (i+1+ADC_KEY1_TAB_SIZE);
			}
		#else
			return (i+1+ADC_KEY1_TAB_SIZE);
		#endif

		#else
			//key_printf("ad_onlykey2_scan=%d, id:%d\n", GET_KEY2_DATA, (i+1));
			return (i+1);
		#endif
		}
	#endif
	}
#endif

#if defined(_SL6812_PARTY_CONTROL_)
#if defined(_SPECIAL_PARTY_CONTROL_)
    key = (GET_KEY3_DATA/4);
    if(key < 255)
    {
    #if defined(ADC3_KEY1_TEST_VALUE)
    	for(i=0;i<ADC_KEY3_TAB_SIZE;i++)
    	{
    		if((key >= ADC3_KEY_TAB[i].KEY_MIN) && (key <= ADC3_KEY_TAB[i].KEY_MAX))break;
    	}
    	if(i==ADC_KEY3_TAB_SIZE)return KEY_VALUE_NULL;
    	else
    	{
    	#if defined(ADC2_KEY1_TEST_VALUE)
    		//key_printf("ad_key3_scan=%d, id:%d\n", GET_KEY3_DATA/4, (i+2+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE));
    		return (i+2+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE);
    	#else
    		//key_printf("ad_onlykey2_scan=%d, id:%d\n", GET_KEY2_DATA, (i+1));
    		return (i+1);
    	#endif
    	}
    #endif
    }
#else
    key = GET_KEY3_DATA;
    key *= ADK_AMP;
    if(key < KEY_ADC_MAX)
    {
    #if defined(ADC3_KEY1_TEST_VALUE)
    	for(i=0;i<ADC_KEY3_TAB_SIZE;i++)
    	{
    		if((key >= ADC3_KEY_TAB[i].KEY_MIN) && (key <= ADC3_KEY_TAB[i].KEY_MAX))break;
    	}
    	if(i==ADC_KEY3_TAB_SIZE)return KEY_VALUE_NULL;
    	else
    	{
    	#if defined(ADC2_KEY1_TEST_VALUE)
    		//key_printf("ad_key3_scan=%d, id:%d\n", GET_KEY3_DATA, (i+2+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE));
    		return (i+2+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE);
    	#else
    		//key_printf("ad_onlykey2_scan=%d, id:%d\n", GET_KEY2_DATA, (i+1));
    		return (i+1);
    	#endif
    	}
	#endif
	}
#endif
#endif

#if defined(_SL6812_KEY_FUNTION_)
	key_down_time = 0;
#endif
#if defined(_SL6812_TEST_LCD_)
	key_up_flag = FALSE;
	key_up_time = 0;
#endif
	return KEY_VALUE_NULL;
}

#elif defined(_SUPPORT_TOUCH_KEY_)
extern uint8 Read_Touch_Value(uint8 Reg);
uint8 ad_key_scan(void)
{
	uint8  TouchValueA,TouchValueB;
	uint16 TouchValueC;

#if defined(_ENABLE_VR_KEY_)
	if(GET_ENCODE_DATA < 3)
	{
	#if defined(_XM007_SPECIAL_MUTE_)
		if(global.sys_power)
		{
			global.xm_mute_flag = TRUE;
		}
	#endif
		return 1;
	}
	else
	{
		if(setup.touch_init)
		{
			TouchValueA = Read_Touch_Value(0x34);
			TouchValueB = Read_Touch_Value(0x35);

			TouchValueC = TouchValueB*256+TouchValueA;

			if(TouchValueC != 0)
			{
				//ew_printf("TouchValueA:0x%x\n", TouchValueA);
				//ew_printf("TouchValueB:0x%x\n", TouchValueB);
				//ew_printf("TouchValueC:0x%x\n", TouchValueC);
			}

		#if defined(_XM007_SPECIAL_BACKLIGHT_)
			if(!global.sys_power)
			{
				if((TouchValueC == 0x01)||(TouchValueC == 0x02)||(TouchValueC == 0x04)||(TouchValueC == 0x08)||(TouchValueC == 0x10)
				||(TouchValueC == 0x20)||(TouchValueC == 0x40)||(TouchValueC == 0x80)||(TouchValueC == 0x100)||(TouchValueC == 0x200)
				||(TouchValueC == 0x400)||(TouchValueC == 0x800)||(TouchValueC == 0x1000)||(TouchValueC == 0x2000)||(TouchValueC == 0x4000))
				{
					global.off_flag = TRUE;
					global.off_time = 100;
				}
			}
		#endif

			switch(TouchValueC)
			{
				case 0x01:
					return 2;
					break;
				case 0x02:
					return 3;
					break;
				case 0x04:
					return 4;
					break;
				case 0x08:
					return 5;
					break;
				case 0x10:
					return 6;
					break;
				case 0x20:
					return 7;
					break;
				case 0x40:
					return 8;
					break;
				case 0x80:
					return 9;
					break;
				case 0x100:
					return 10;
					break;
				case 0x200:
					return 11;
					break;
				case 0x400:
					return 12;
					break;
				case 0x800:
					return 13;
					break;
				case 0x1000:
					return 14;
					break;
				case 0x2000:
					return 15;
					break;
				case 0x4000:
					return 16;
					break;
			}
			return KEY_VALUE_NULL;
		}
		else
		{
			return KEY_VALUE_NULL;
		}
	}
#endif
}

#else

#if defined(_ENABLE_PARTY_CONTROL_DELAY)
#define KEY_GET_VLAUE_TIME      300  //15秒
uint8 key_value=0;
uint32 key_time=0;
uint8 key_flag=0;
#endif

#if defined(_BL7680_PASSWORD_SET_)
uint32 key_down_time=0;
#endif

uint8 ad_key_scan(void)
{

#if 1

	return Key_State_Scan();

#else
#if defined(GET_KEY1_DATA)||defined(GET_KEY2_DATA)
	uint8 i;
	uint8 key;
#endif

#if defined(_FY700B_PARTY_CONTROL_)
	static uint8 AdKeyFlag ;
#endif

#if defined(_ENABLE_TEL_MUTE_DETECT_)
	if(global.tel_mute_flag)
	{
		return 0;
	}
#endif

#if defined(GET_KEY1_DATA)

	key = GET_KEY1_DATA;
	key *= ADK_AMP;

#if defined(DTH_USE_KEY1_DETECT)
	if(key>245)
	{
	   setup.dth_detect = 1;
	}
	else if((key>230)&&(key<245))
	{
	   setup.dth_detect = 0;
	}
#endif
	//key_printf("11ad_key1_scan=%d\n", GET_KEY1_DATA);
		if(key < KEY_ADC_MAX)
		{
			#if defined(ADC1_KEY1_TEST_VALUE)
			for(i = 0; i < ADC_KEY1_TAB_SIZE; i++)
			{
				if((key >= ADC1_KEY_TAB[i].KEY_MIN) && (key <= ADC1_KEY_TAB[i].KEY_MAX))break;
			}
			if(i==ADC_KEY1_TAB_SIZE)return KEY_VALUE_NULL;
			else
			{
				key_printf("scan=%d, id:%d\n", GET_KEY1_DATA, (i+1));
			#if defined(_BL7680_PASSWORD_SET_)
				if(((GET_KEY1_DATA > 10)&&(GET_KEY1_DATA < 14)) && ((GET_KEY2_DATA > 10)&&(GET_KEY2_DATA < 14)))
				{
					key_down_time++;
					if(key_down_time < 5)
					{
						return 0;
					}
					else
					{
						return 27;
					}
				}
				else
				{
					return (i+1);
				}
			#elif defined(_YH1701_SPECIAL_IR_)
				if(key/4 > 1)
				{
					setup.ir_power = FALSE;
					setup.ir_power_time = 0;
				}

				if((setup.ir_power)&&(key/4 <2))
				{
					setup.ir_power_time--;
					if(!setup.ir_power_time)
					{
						setup.ir_power = FALSE;
						return KEY_VALUE_NULL;
					}
				}
				else
				{
					setup.ir_power_time = 0;
					return (i+1);
				}
			#else
				return (i+1);
			#endif
			}
		#endif
		}
#endif

#if defined( GET_KEY2_DATA )
		key = GET_KEY2_DATA;
		key *= ADK_AMP;
		//key_printf("22ad_key2_scan=%d\n", GET_KEY2_DATA);
		if(key < KEY_ADC_MAX)
		{
		#if defined(ADC2_KEY1_TEST_VALUE)
			for(i=0;i<ADC_KEY2_TAB_SIZE;i++)
			{
				if((key >= ADC2_KEY_TAB[i].KEY_MIN) && (key <= ADC2_KEY_TAB[i].KEY_MAX))break;
			}
			if(i==ADC_KEY2_TAB_SIZE)return KEY_VALUE_NULL;
			else
			{
			#if defined(ADC1_KEY1_TEST_VALUE)
			    key_printf("ad_key2_scan=%d, id:%d\n", GET_KEY2_DATA, (i+1+ADC_KEY1_TAB_SIZE));
				return (i+1+ADC_KEY1_TAB_SIZE);
			#else
				//key_printf("ad_onlykey2_scan=%d, id:%d\n", GET_KEY2_DATA, (i+1));
				return (i+1);
			#endif
			}
		#endif
		}
#endif

#if defined( SUPPORT_PARTY_CONTROL )
		key = GET_KEY3_DATA;
		key *= ADK_AMP;
		//key_printf("33ad_key3_scan=%d\n", GET_KEY3_DATA);
		if(key < KEY_ADC_MAX)
		{
		#if defined(ADC3_KEY1_TEST_VALUE)
			for(i=0;i<ADC_KEY3_TAB_SIZE;i++)
			{
				if((key >= ADC3_KEY_TAB[i].KEY_MIN) && (key <= ADC3_KEY_TAB[i].KEY_MAX))break;
			}
			if(i==ADC_KEY3_TAB_SIZE)return KEY_VALUE_NULL;
			else
			{
			#if defined(_ENABLE_PARTY_CONTROL_DELAY)
				if(key_value!=key)
				{
					key_value = key;
					key_flag = 0;
					key_time = KEY_GET_VLAUE_TIME;
					//key_printf("key_value = %d\n",key_value);
				}
				if(key_value == key)
				{
					if(!key_flag)
					{
						key_time--;
						key_printf("key_time = %d\n",key_time);
					}
				}
				if(!key_time)
				{
					key_flag = 1;
				}
				if(key_flag)
				{
					key_puts("goto _KEY_VALUE_AGIN_GET\n");
					return KEY_VALUE_NULL;
				}
			#endif

			#if defined(ADC3_KEY1_TEST_VALUE)
				key_printf("ad_key3_scan=%d, id:%d\n", GET_KEY3_DATA, (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE));
				return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE);
			#else
				//key_printf("ad_onlykey3_scan=%d, id:%d\n", GET_KEY3_DATA, (i+1));
				return (i+1);
			#endif
			}
		#endif
		}
#if defined(_ENABLE_PARTY_CONTROL_DELAY)
	else
	{
		//按键松开
		key_flag = 0;
		key_time = KEY_GET_VLAUE_TIME;
	}
#endif
#endif

#if defined(_FY700B_PARTY_CONTROL_)
	key = GET_KEY3_DATA;
	key *= ADK_AMP;

	if(key < KEY_ADC_MAX)
	{
		//key_printf("ad3_key_valuen..............=%d\n", key);
		AdKeyFlag = TRUE ;
		//key_printf("ad3_key_valuen..............=%d\n", AdKeyFlag);
	#if 0
	#if defined(ADC3_KEY1_TEST_VALUE)
		for(i=0;i<ADC_KEY3_TAB_SIZE;i++)
		{
			if((key >= ADC3_KEY_TAB[i].KEY_MIN) && (key <= ADC3_KEY_TAB[i].KEY_MAX))break;
		}
		if(i==ADC_KEY3_TAB_SIZE)
		{
			return KEY_VALUE_NULL;
		}
		else
		{
		#if defined(ADC3_KEY1_TEST_VALUE)
			key_printf("ad_key3_scan=%d, id:%d\n", GET_KEY3_DATA, (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE));
			//return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE);
		#endif
		}
	#endif
	#endif
	}

#if !defined(_DISABLE_PARTY_KEY2_)
	key = GET_KEY4_DATA;
	key *= ADK_AMP;
	//key_printf("33ad_key4_scan=%d\n", GET_KEY4_DATA);

	if(key < KEY_ADC_MAX)
	{
		if(AdKeyFlag )
		{
			AdKeyFlag = 0 ;
			//key_printf("AdKeyFlag...........=%d\n", AdKeyFlag);
			//key_printf("ad4_key_valuen...........=%d\n", key);
		#if defined(ADC4_KEY1_TEST_VALUE)
			for(i=0;i<ADC_KEY4_TAB_SIZE;i++)
			{
				if((key >= ADC4_KEY_TAB[i].KEY_MIN) && (key <= ADC4_KEY_TAB[i].KEY_MAX))break;
			}
			if(i==ADC_KEY4_TAB_SIZE)
			{
				return KEY_VALUE_NULL;
			}
			else
			{
			#if defined(ADC4_KEY1_TEST_VALUE)
				//key_printf("ad_key4_scan=%d, id:%d\n", GET_KEY4_DATA, (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE+8));
				return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE+8);
			#endif
			}
		#endif
		}
		else
		{
			//key_printf("ad4_key_valuen...........=%d\n", key);
		#if defined(ADC4_KEY1_TEST_VALUE)
			for(i=0;i<ADC_KEY4_TAB_SIZE;i++)
			{
				if((key >= ADC4_KEY_TAB[i].KEY_MIN) && (key <= ADC4_KEY_TAB[i].KEY_MAX))break;
			}
			if(i==ADC_KEY4_TAB_SIZE)
			{
				return KEY_VALUE_NULL;
			}
			else
			{
			#if defined(ADC4_KEY1_TEST_VALUE)
				//key_printf("ad_key4_scan=%d, id:%d\n", GET_KEY4_DATA, (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE));
				return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE);
			#endif
			}
		#endif
		}
	}
#endif
#endif

#if defined(_XZC1668_ADKEY_CONTROL_)||defined(_YJ3993_ADKEY_CONTROL_)
    key = GET_KEY3_DATA;
    key *= ADK_AMP;
    //key_printf("33ad_key3_scan=%d\n", GET_KEY3_DATA);
    if(key < KEY_ADC_MAX)
    {
    #if defined(ADC3_KEY1_TEST_VALUE)
    	for(i=0;i<ADC_KEY3_TAB_SIZE;i++)
    	{
    		if((key >= ADC3_KEY_TAB[i].KEY_MIN) && (key <= ADC3_KEY_TAB[i].KEY_MAX))break;
    	}
    	if(i==ADC_KEY3_TAB_SIZE)return KEY_VALUE_NULL;
    	else
    	{
    	#if defined(ADC3_KEY1_TEST_VALUE)
    		key_printf("ad_key3_scan=%d, id:%d\n", GET_KEY3_DATA, (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE));
    		return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE);
    	#else
    		//key_printf("ad_onlykey3_scan=%d, id:%d\n", GET_KEY3_DATA, (i+1));
    		return (i+1);
    	#endif
    	}
    #endif
	}

    key = GET_KEY4_DATA;
    key *= ADK_AMP;
    //key_printf("44ad_key4_scan=%d\n", GET_KEY4_DATA);
    if(key < KEY_ADC_MAX)
    {
    #if defined(ADC4_KEY1_TEST_VALUE)
    	for(i=0;i<ADC_KEY4_TAB_SIZE;i++)
    	{
    		if((key >= ADC4_KEY_TAB[i].KEY_MIN) && (key <= ADC4_KEY_TAB[i].KEY_MAX))break;
    	}
    	if(i==ADC_KEY3_TAB_SIZE)return KEY_VALUE_NULL;
    	else
    	{
    	#if defined(ADC4_KEY1_TEST_VALUE)
    		key_printf("ad_key4_scan=%d, id:%d\n", GET_KEY4_DATA, (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE+ADC_KEY3_TAB_SIZE));
    		return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE+ADC_KEY3_TAB_SIZE);
    	#else
    		//key_printf("ad_onlykey4_scan=%d, id:%d\n", GET_KEY4_DATA, (i+1));
    		return (i+1);
    	#endif
    	}
	#endif
	}
#endif

#if defined(_KLD3300_PARTY_CONTROL_)
	key = GET_KEY3_DATA;
	key *= ADK_AMP;
	//key_printf("33ad_key3_scan=%d\n", GET_KEY3_DATA);
	if(key < KEY_ADC_MAX)
	{
	#if defined(ADC3_KEY1_TEST_VALUE)
		for(i=0;i<ADC_KEY3_TAB_SIZE;i++)
		{
			if((key >= ADC3_KEY_TAB[i].KEY_MIN) && (key <= ADC3_KEY_TAB[i].KEY_MAX))break;
		}
		if(i==ADC_KEY3_TAB_SIZE)return KEY_VALUE_NULL;
		else
		{
		#if defined(ADC3_KEY1_TEST_VALUE)
			//key_printf("ad_key3_scan=%d, id:%d\n", GET_KEY3_DATA, (i+1+ADC_KEY2_TAB_SIZE));
			return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE);
		#else
			//key_printf("ad_onlykey3_scan=%d, id:%d\n", GET_KEY3_DATA, (i+1));
			return (i+1);
		#endif
		}
	#endif
	}

	key = GET_KEY4_DATA;
	key *= ADK_AMP;
	//key_printf("44ad_key4_scan=%d\n", GET_KEY4_DATA);
	if(key < KEY_ADC_MAX)
	{
	#if defined(ADC4_KEY1_TEST_VALUE)
		for(i=0;i<ADC_KEY4_TAB_SIZE;i++)
		{
			if((key >= ADC4_KEY_TAB[i].KEY_MIN) && (key <= ADC4_KEY_TAB[i].KEY_MAX))break;
		}
		if(i==ADC_KEY3_TAB_SIZE)return KEY_VALUE_NULL;
		else
		{
		#if defined(ADC4_KEY1_TEST_VALUE)
			//key_printf("ad_key4_scan=%d, id:%d\n", GET_KEY4_DATA, (i+1+ADC_KEY3_TAB_SIZE));
			return (i+1+ADC_KEY1_TAB_SIZE+ADC_KEY2_TAB_SIZE+ADC_KEY3_TAB_SIZE);
		#else
			//key_printf("ad_onlykey4_scan=%d, id:%d\n", GET_KEY4_DATA, (i+1));
			return (i+1);
		#endif
		}
	#endif
	}
#endif

#if defined(_BL7680_PASSWORD_SET_)
	key_down_time = 0;
#endif
#endif

	return KEY_VALUE_NULL;
}
#endif

#if defined(_SUPPORT_REAL_VBAR_)
uint8 ad_vbar_scan(void)
{
	return GET_VBAR_DATA;
	key_printf("GET_VBAR_DATA=%d\n", GET_VBAR_DATA);
}
#endif

