#ifndef __UI_DISC_H__
#define __UI_DISC_H__


#define DISC_DISP_DEBUG
#ifdef DISC_DISP_DEBUG
#define disc_disp_printf 			ew_printf
#define disc_disp_puts 				ew_puts
#else
#define disc_disp_printf(...)
#define disc_disp_puts(...)
#endif

enum{
	DISC_SOURCE_NULL = 0,
	DISC_SOURCE_DISC,
	DISC_SOURCE_USB,
	DISC_SOURCE_CARD,	
};

enum{
	DISC_ERROR_NULL = 0,
	DISC_ERROR_DRIVER,
	DISC_ERROR_FILE,
	DISC_ERROR_NO_FILE,
};

enum{
	DISC_STATUS_IDLE = 0,
	DISC_STATUS_PLAYE,
	DISC_STATUS_PAUSE,
	DISC_STATUS_STOP,
	DISC_STATUS_FORWARD,
	DISC_STATUS_BACKWARD,
	DISC_STATUS_UPGRADE,
};

enum{
	DISC_MODE_REPEAT_OFF = 0,
	DISC_MODE_REPEAT_ONE,
	DISC_MODE_REPEAT_FOLDER,
	DISC_MODE_REPEAT_ALL,
	DISC_MODE_SHUFFLE,
	DISC_MODE_INTRO,
	DISC_MODE_ERROR,
};

enum{
	DISC_MEDIA_NULL = 0,
	DISC_MEDIA_CD,
	DISC_MEDIA_WMA,
	DISC_MEDIA_ASF,
	DISC_MEDIA_WAV,
	DISC_MEDIA_MP3,
	DISC_MEDIA_MP4,
	DISC_MEDIA_VCD,
	DISC_MEDIA_DVD,
	DISC_MEDIA_JPG,
	DISC_MEDIA_TXT,
	DISC_MEDIA_UNKONW,
};

enum{
	DISC_SEARCH_MODE_INIT = 0,
	DISC_SEARCH_MODE_NORMAL,
	DISC_SEARCH_MODE_TRK_SCH,
	DISC_SEARCH_MODE_FILE_SCH,
	DISC_SEARCH_MODE_DIR_SCH,	
};
//	init status
enum{
	DISC_SEARCH_STATUS_INIT_LOAD,
	DISC_SEARCH_STATUS_INIT_MEDIA,
	DISC_SEARCH_STATUS_INIT_TOTAL,
	DISC_SEARCH_STATUS_INIT_DELAY,
	DISC_SEARCH_STATUS_INIT_PLAY,
	DISC_SEARCH_STATUS_INIT_END,
};
//	disp status
enum{
	DISC_SEARCH_STATUS_DISP_TIME = 0,
	DISC_SEARCH_STATUS_DISP_FILE_NAME,
	DISC_SEARCH_STATUS_DISP_SONG_NAME,
	DISC_SEARCH_STATUS_DISP_ARTIST,
	DISC_SEARCH_STATUS_DISP_ALBUM,
	DISC_SEARCH_STATUS_DISP_DIR,
	DISC_SEARCH_STATUS_DISP_MSG,
};
//	track search status	
enum{
	DISC_SEARCH_STATUS_TRK_SCH_TITLE = 0,
	DISC_SEARCH_STATUS_TRK_SCH_INPUT,
	DISC_SEARCH_STATUS_TRK_SCH_ERROR,
	DISC_SEARCH_STATUS_TRK_SCH_SEARCH,
	DISC_SEARCH_STATUS_TRK_SCH_END,
};
//	file search status
enum{
	DISC_SEARCH_STATUS_FILE_SCH_TITLE = 0,
	DISC_SEARCH_STATUS_FILE_SCH_INPUT,
	DISC_SEARCH_STATUS_FILE_SCH_SEARCH,
	DISC_SEARCH_STATUS_FILE_SCH_ERROR,
	DISC_SEARCH_STATUS_FILE_SCH_SELECT,
	DISC_SEARCH_STATUS_FILE_SCH_PLAYER,
	DISC_SEARCH_STATUS_FILE_SCH_END,
};
//	dir search status
enum{
	DISC_SEARCH_STATUS_DIR_SCH_TITLE = 0,
	DISC_SEARCH_STATUS_DIR_SCH_DIR_SELECT, 
	DISC_SEARCH_STATUS_DIR_SCH_FILE_SELECT,
	DISC_SEARCH_STATUS_DIR_SCH_PLAYER,
	DISC_SEARCH_STATUS_DIR_SCH_END,
};


typedef struct{
	uint8 status;
	uint8 mode;
	uint8 search_mode;
	uint8 search_status;
	uint8 media;
	uint8 error;
#if defined(_FY7000C_DISPLAY_BUFFER_)
    uint8 disp_buffer[13];
#else	
	uint8 disp_buffer[8];
#endif
	uint8 disp_num;
	uint8 dot_flag;
}disc_disp_info_t;

typedef struct{
	disc_disp_info_t info;
	uint8 source;
	uint8 disc_time;
	uint8 disc_state;
}disc_disp_t;


#endif  /*  __UI_PLAY_H__  */

