#ifndef __UI_RES_H__
#define __UI_RES_H__


typedef enum
{
	LANG_ID_NULL = 0,		// 0
	
	//system    
	LANG_ID_SYSTEM_WELCOME,
	LANG_ID_SYSTEM_GOODBYE,
	
	//radio                
	LANG_ID_RADIO,
	LANG_ID_RADIO_ST_ON,
	LANG_ID_RADIO_ST_OFF,	// 5
	LANG_ID_RADIO_LOC_ON,
	LANG_ID_RADIO_LOC_OFF,
	LANG_ID_RADIO_MANUAL,
	LANG_ID_RADIO_AUTO,
    LANG_ID_RADIO_AREA_EUR,// 10
    LANG_ID_RADIO_AREA_USA,
#if defined(_SUPPORT_THREE_AREA_)||defined(_SUPPORT_FOUR_AREA_)
	LANG_ID_RADIO_AREA_LATIN,
#endif
#if defined(_SUPPORT_FOUR_AREA_)
	LANG_ID_RADIO_AREA_ASIA,
#endif
#if defined(DAB_MODLE)
	//DAB    
	LANG_ID_DAB,
#endif
#if defined(_SUPPORT_TAPE_)
	LANG_ID_TAPE,
	LANG_ID_TAPE1,
	LANG_ID_TAPE_A,
	LANG_ID_TAPE_B,
#endif
#if defined(EASYESY_APP_ONOFF)
	LANG_ID_APP_ON,
	LANG_ID_APP_OFF,
#endif

	//music                       
	LANG_ID_MUSIC_USB,
	LANG_ID_MUSIC_SD,
	LANG_ID_MUSIC_LOAD,
	LANG_ID_MUSIC_MODE_REPEAT_ALL,//15
	LANG_ID_MUSIC_MODE_REPEAT_ONE,
	LANG_ID_MUSIC_MODE_REPEAT_FOLDER,
	LANG_ID_MUSIC_MODE_REPEAT_OFF,
	LANG_ID_MUSIC_MODE_RDM_ON,
	LANG_ID_MUSIC_MODE_RDM_OFF,//20
	LANG_ID_MUSIC_MODE_INT_ON,
	LANG_ID_MUSIC_MODE_INT_OFF,
#if defined(_SUPPORT_DISC_)
	LANG_ID_MUSIC_DISC,
	LANG_ID_DISC_EJECT,
#if defined(NEED_NO_DISC_DISP)
	LANG_ID_NO_DISC,
#endif
#endif

#if defined(_SUPPORT_AUX1_)
	LANG_ID_AUX1_IN,
#endif
	//linein                      
	LANG_ID_AUX_IN,

#if defined(_ENABLE_MODE_CHANNEL_)
	LANG_ID_OPTICAL,
	LANG_ID_TV,
	LANG_ID_DVD,
#endif

#if defined(_SUPPORT_SUB_)
	LANG_ID_OTHERS_SUB_IN,
	LANG_ID_OTHERS_SUB_EXT,
#endif

#if defined(_SEL_ADD_TIME_SELECT_)
	LANG_ID_24H,
	LANG_ID_12H,
#endif

	//bluetooth                   
	LANG_ID_BLUETOOTH,
	LANG_ID_BT_ON,				//25
	LANG_ID_BT_OFF,
	LANG_ID_BT_CONNECT,
	LANG_ID_BT_CONNECTD,
	LANG_ID_BT_PLAY,
	LANG_ID_BT_PAUSE,			//30
	LANG_ID_BT_INCOMING,
	LANG_ID_BT_OUTGOING,
	LANG_ID_BT_HFP,
	LANG_ID_BT_PHONE,
	LANG_ID_BT_ERROR,			//35
	LANG_ID_BT_REDIAL,
	LANG_ID_BT_DIAL,
#if defined(_SUPPORT_CALL_RECORDS_)
	LANG_ID_BT_NO_CALL,
#endif
#if defined(_SUPPORT_IPHONE_SIR_)
	LANG_ID_SIR,
#endif
#if defined(_TALKING_VOICE_DISPLAY_)
	LANG_ID_BT_TRANSFER,
#endif
#if defined(HANGUP_DISP_HANGUP)
	LANG_ID_BT_END,
#endif
#if defined(_ENABLE_BT_AUDIO_DISP_)
	LANG_ID_BT_NEXT,
	LANG_ID_BT_PREV,
#endif
#if defined(_SL6812A_MODE_FUNTION_)
	LANG_ID_NO_MEDIA,
#endif

#if defined(_ENABLE_RESET_DISPLAY_)
	LANG_ID_RESET,
#endif

	//upgrade                     
	LANG_ID_UPGRADE,
	LANG_ID_UPGRADE_SUCCEED,
	LANG_ID_UPGRADE_FAIL,		//40
	
	//others                      
	LANG_ID_OTHERS_VOLUME,
	LANG_ID_OTHERS_MUTE_ON,
	LANG_ID_OTHERS_MUTE_OFF,
	LANG_ID_OTHERS_LOUD_ON,
	LANG_ID_OTHERS_LOUD_OFF,//	45
	LANG_ID_OTHERS_EQ_OFF,
	LANG_ID_OTHERS_EQ_FLAT,
	LANG_ID_OTHERS_EQ_CLASSIC,
	LANG_ID_OTHERS_EQ_POP,
	LANG_ID_OTHERS_EQ_ROCK,	//50
	LANG_ID_OTHERS_EQ_JAZZ,
	LANG_ID_OTHERS_BASS,
	LANG_ID_OTHERS_TREBLE,
	LANG_ID_OTHERS_BAL,
	LANG_ID_OTHERS_FAD,		//55
#if defined(_ENABLE_AP3768_EQ_MODE_)
	LANG_ID_OTHERS_EQ_PEOPLE,
	LANG_ID_OTHERS_EQ_SOFT,
	LANG_ID_OTHERS_EQ_ELECTRIC,
#endif
#if defined(_SPECIAL_TL2000_SET_)		
	LANG_ID_OTHERS_A_VOLUME,
	LANG_ID_OTHERS_B_VOLUME,
#endif
#if defined(_ENABLE_TALK_VOL_)
	LANG_ID_OTHERS_TAIK_VOLUME,
#endif
#if defined(_ENABLE_BT_ON_OFF_)
	LANG_ID_OTHERS_BT_ON,
	LANG_ID_OTHERS_BT_OFF,
#endif
#if defined(_CHANGE_DEF_VOL_)		
	LANG_ID_OTHERS_P_VOL,
#endif
	LANG_ID_OTHERS_SUBWOOFER_ON,
	LANG_ID_OTHERS_SUBWOOFER_OFF,
	LANG_ID_OTHERS_BEEP_ON,
	LANG_ID_OTHERS_BEEP_OFF,//59
#if REC_EN
	LANG_ID_RECORD,
#if defined(_ENABLE_RECORD_DISPLAY_)
	LANG_ID_PAUSE,
#endif
#endif
#if defined(_ENABLE_TEL_MUTE_DETECT_)
	LANG_ID_TEL_MUTE,
#endif
#if defined(_SUPPORT_SUBWOOFER_MODE2_)
	LANG_ID_SUB,
#endif
#if defined(_SUPPORT_SUBWOOFER3_)||defined(_ENABLE_AP3768_SUBWOOFER_)
    LANG_ID_OTHERS_SUBWOOFER1_ON,
    LANG_ID_OTHERS_SUBWOOFER1_OFF,
#endif

#if defined(AUDIO_SUB_LEVEL_SET)
	LANG_ID_SUB_CUT_CTRL,
#endif

#if defined(_ENABLE_7419_MIDDLE_)
	LANG_ID_OTHERS_MIDDLE,
#endif

#if defined(_ENABLE_ID3_ON_OFF_)||defined(_ENABLE_ID3_SET_)
	LANG_ID_ID3_ON,
	LANG_ID_ID3_OFF,
#endif

#if defined(_SUPPORT_PANEL_LIGHT_)||defined(_SUPPORT_30P60_LIGHT_)
    LANG_ID_BLUE,
    LANG_ID_GREEN,
	LANG_ID_CYAN,
	LANG_ID_RED,
	LANG_ID_FUCHSINE,
	LANG_ID_YELLOW,
	LANG_ID_WHITE,
	LANG_ID_AUTO,
#endif

#if defined(_ENABLE_DEFAULT_CONTROL_)||defined(ADD_ADJUST_DEFAULT_VOL)
	LANG_ID_OTHERS_DEFAULT_VOLUME,
#endif

#if defined(SUPPORT_LED_ADJUST)
	LANG_ID_LED_LOW,
	LANG_ID_LED_MID,
	LANG_ID_LED_HIGH,
#endif

#if defined(_ADJUST_A_B_SPK_)
	LANG_ID_A_SPK_ON,
	LANG_ID_A_SPK_OFF,
	LANG_ID_B_SPK_ON,
	LANG_ID_B_SPK_OFF,
#endif

#if defined(_MR889_SPECAIL_KEY_)
	LANG_ID_CONTROL_SPK_ON,
	LANG_ID_CONTROL_SPK_OFF,
#endif

#if defined(_ENABLE_FAD_FUNTION_)
	LANG_ID_FAD_SINGLE_F,
	LANG_ID_FAD_SINGLE_R,
	LANG_ID_FAD_ALL,
#endif

#if defined(_ENABLE_RDS_ON_OFF_)
	LANG_ID_RDS_ON,
	LANG_ID_RDS_OFF,
#endif

#if defined(SUPPORT_ALARM_FUNC_)
	LANG_ID_OTHERS_ALARM_ON,
	LANG_ID_OTHERS_ALARM_OFF,
	LANG_ID_OTHERS_ALARM_RINGING,
#endif

#if defined(_ENABLE_TIME_DISP_)
	LANG_ID_OTHERS_DISP_ON,
	LANG_ID_OTHERS_DISP_OFF,
#endif

#if defined(_SUPPORT_MIC_OK_)
	LANG_ID_MIC,
#endif

#if defined(_SUPPORT_CAN_MODEL_)
	LANG_ID_CAN,
#endif

#if defined(_SUPPORT_REVERSE_MODEL_)
    LANG_ID_REVE,
#endif

#if defined(_ENABLE_PASSWORD_INPUT_)
	LANG_ID_PASSWORD,
	LANG_ID_ERROR,
#endif

#if defined(_SUPPORT_CAN_UART_)
	LANG_ID_CAN_ERR,
	LANG_ID_CAN_SPEED,
	LANG_ID_CAN_DISTANCE,
	LANG_ID_CAN_ELECTRIC,
	LANG_ID_CAN_GEARS,
	LANG_ID_CAN_P1,
	LANG_ID_CAN_P2,
#endif

#if defined(_SUPPORT_POWER_ON_PASSWORD_)
	LANG_ID_PASSWORD,
	LANG_ID_ERROR,
#endif

#if defined(_SUPPORT_PASSWORD_DISPLAY_)
    LANG_ID_PASSWORD,
    LANG_ID_ERROR1,
    LANG_ID_ERROR2,
    LANG_ID_ERROR3,
    LANG_ID_ERROR4,
    LANG_ID_ERROR5,
#endif

#if defined(_SL6812_KEY_FUNTION_)
	LANG_ID_SPM,
#endif

#if defined(_BT_DISCONNECT_DISPLAY_)
    LANG_ID_CONNECTD,
#endif

#if defined(_ENABLE_PASSWORD_SET_)
	LANG_ID_PWD_SET,
	LANG_ID_PWD_SET_DISPLAY,
#endif

#if defined(_PASSWORD_TRUE_DISPLAY_)
	LANG_ID_PWD_CORRECT,
#endif

#if defined(_ENABLE_MENU_FUNTION_)
	LANG_ID_OTHERS_SETUP,
	LANG_ID_OTHERS_DEFAULT_VOLUME,
	LANG_ID_OTHERS_LOG_ON,
	LANG_ID_OTHERS_LOG_OFF,
#endif

#if defined(_ENABLE_PLAY_ERROR_)
	LANG_ID_USB_ERR,
	LANG_ID_SD_ERR,
#endif

#if defined(_SD_NO_FILE_DISPLAY_ERR_)
	LANG_ID_MUSIC_ERR,
#endif

#if defined(_FAD_BAL_FUNTION_)
	LANG_ID_FL,
	LANG_ID_FR,
	LANG_ID_RL,
	LANG_ID_RR,
#endif

#if defined(_SUPPORT_10_EQ_FUNTION_)
	LANG_ID_OTHERS_60HZ,
	LANG_ID_OTHERS_150HZ,
	LANG_ID_OTHERS_400HZ,
	LANG_ID_OTHERS_1KHZ,
	LANG_ID_OTHERS_2KHZ,
	LANG_ID_OTHERS_3KHZ,
	LANG_ID_OTHERS_7KHZ,
	LANG_ID_OTHERS_10KHZ,
	LANG_ID_OTHERS_15KHZ,
	LANG_ID_OTHERS_20KHZ,
#endif

#if defined(_ENABLE_SUB_DETECT_)
	LANG_ID_ON,
	LANG_ID_OFF,
#endif

#if defined(_XM003_MODE_DISPLAY_)
	LANG_ID_NO_SRC,
#endif

#if defined(_FY7555_LCD_DISPLAY_)
	LANG_ID_SET,
#endif

#if defined(_FEIYIN_MENU_TIME_)
	LANG_ID_CLK_SET,
#endif

#if defined(_ENABLE_RADIO_RDS_)
	//band rds	
	LANG_ID_RDS_TRAFFIC,
	LANG_ID_RDS_EON_TA,
	LANG_ID_RDS_NO_TP_TA,
	LANG_ID_RDS_TA_SEEK,
	LANG_ID_RDS_PI_SEEK,
	LANG_ID_RDS_PTY_SEEK,
	LANG_ID_RDS_AF_ON,
	LANG_ID_RDS_AF_OFF,
	LANG_ID_RDS_TA_ON,
	LANG_ID_RDS_TA_OFF,
	LANG_ID_RDS_TA_PAUSE,
	LANG_ID_RDS_REG_LOC,
	LANG_ID_RDS_REG_DX,
	LANG_ID_RDS_EON_ON,
	LANG_ID_RDS_EON_OFF,
	LANG_ID_RDS_RETURN_LONG,
	LANG_ID_RDS_RETURN_SHORT,
	LANG_ID_RDS_MASK_ALL,
	LANG_ID_RDS_MASK_DIP,
	LANG_ID_RDS_ALARM_ON,
	LANG_ID_RDS_ALARM_OFF,
	LANG_ID_RDS_TIME_SYNC,
	LANG_ID_RDS_TIME_ASYNC,
#if defined(ENABLE_TA_VOL_SET)
	LANG_ID_RDS_TA_VOL,
#endif	
	LANG_ID_RDS_SEARCH,
	LANG_ID_RDS_PTY_OFF,
	LANG_ID_RDS_PTY_MUSIC,
	LANG_ID_RDS_PTY_SPEECH,
	LANG_ID_RDS_FOUND,
	LANG_ID_RDS_NO_FOUND,

	LANG_ID_RDS_PTY_0,
	LANG_ID_RDS_PTY_31 = LANG_ID_RDS_PTY_0 + 31,
	
	LANG_ID_RBDS_PTY_0,
	LANG_ID_RBDS_PTY_31 = LANG_ID_RBDS_PTY_0 + 31,
	
#endif
/*--------------------------------------------------------------------------------------------------------------------*/
	
	LANG_ID_MAX,
}ui_lang_id_e;

extern uint8 ui_lang_res_search(ui_lang_id_e, uint8 *, uint8);

#if defined(_FY7555_LCD_DISPLAY_)
extern uint8 ui_lang_lcd_search(ui_lang_id_e, uint8 *, uint8);
#endif

#endif /* __UI_RES_H__ */

