#ifndef _KEY_MAP_H_
#define _KEY_MAP_H_

//进入这里


#define ADC1_KEY1_TEST_VALUE				KEY_ADC_VALUE(0)
#define ADC1_KEY2_TEST_VALUE				KEY_ADC_VALUE(3)
#define ADC1_KEY3_TEST_VALUE				KEY_ADC_VALUE(7)
#define ADC1_KEY4_TEST_VALUE				KEY_ADC_VALUE(12)
#define ADC1_KEY5_TEST_VALUE				KEY_ADC_VALUE(16)
#define ADC1_KEY6_TEST_VALUE				KEY_ADC_VALUE(22)
#define ADC1_KEY7_TEST_VALUE				KEY_ADC_VALUE(27)
#define ADC1_KEY8_TEST_VALUE				KEY_ADC_VALUE(32)
#define ADC1_KEY9_TEST_VALUE				KEY_ADC_VALUE(36)
#define ADC1_KEY10_TEST_VALUE				KEY_ADC_VALUE(45)
#define ADC1_KEY11_TEST_VALUE				KEY_ADC_VALUE(50)
#define ADC1_KEY12_TEST_VALUE				KEY_ADC_VALUE(55)
#define ADC1_KEY13_TEST_VALUE				KEY_ADC_VALUE(60)

#define ADC2_KEY1_TEST_VALUE				KEY_ADC_VALUE(0)
#define ADC2_KEY2_TEST_VALUE				KEY_ADC_VALUE(3)
#define ADC2_KEY3_TEST_VALUE				KEY_ADC_VALUE(7)
#define ADC2_KEY4_TEST_VALUE				KEY_ADC_VALUE(12)
#define ADC2_KEY5_TEST_VALUE				KEY_ADC_VALUE(16)
#define ADC2_KEY6_TEST_VALUE				KEY_ADC_VALUE(22)
#define ADC2_KEY7_TEST_VALUE				KEY_ADC_VALUE(27)
#define ADC2_KEY8_TEST_VALUE				KEY_ADC_VALUE(32)
#define ADC2_KEY9_TEST_VALUE				KEY_ADC_VALUE(36)
#define ADC2_KEY10_TEST_VALUE				KEY_ADC_VALUE(45)
#define ADC2_KEY11_TEST_VALUE				KEY_ADC_VALUE(50)
#define ADC2_KEY12_TEST_VALUE				KEY_ADC_VALUE(55)
#define ADC2_KEY13_TEST_VALUE				KEY_ADC_VALUE(60)

#if defined(_FY700B_PARTY_CONTROL_)
#define ADC3_KEY1_TEST_VALUE				KEY_ADC_VALUE(10)	
#define ADC3_KEY2_TEST_VALUE				KEY_ADC_VALUE(19)
#define ADC3_KEY3_TEST_VALUE				KEY_ADC_VALUE(27)
#define ADC3_KEY4_TEST_VALUE				KEY_ADC_VALUE(32)
#define ADC3_KEY5_TEST_VALUE				KEY_ADC_VALUE(36)	// 35
#define ADC3_KEY6_TEST_VALUE				KEY_ADC_VALUE(45)	// 39
#define ADC3_KEY7_TEST_VALUE				KEY_ADC_VALUE(59)	// 39

#define ADC4_KEY1_TEST_VALUE				KEY_ADC_VALUE(10)	// 9
#define ADC4_KEY2_TEST_VALUE				KEY_ADC_VALUE(18)	// 18
#define ADC4_KEY3_TEST_VALUE				KEY_ADC_VALUE(22)	// 25
#define ADC4_KEY4_TEST_VALUE				KEY_ADC_VALUE(29)	// 30
#define ADC4_KEY5_TEST_VALUE				KEY_ADC_VALUE(35)	// 35
#define ADC4_KEY6_TEST_VALUE				KEY_ADC_VALUE(42)	// 40
#define ADC4_KEY7_TEST_VALUE				KEY_ADC_VALUE(47)	// 46
#define ADC4_KEY8_TEST_VALUE				KEY_ADC_VALUE(54)	// 55
#define ADC4_KEY9_TEST_VALUE				KEY_ADC_VALUE(58)	// 57
#define ADC4_KEY10_TEST_VALUE				KEY_ADC_VALUE(62)	// 61
#endif

/*-------------------------------------------------------------------*/

enum{//enter here
	KEY_VALUE_NULL,// 0
/*---------------------------------------------*/
	KEY_VALUE_POWER,// 1
	KEY_VALUE_EQ_LOUD,// 2
	KEY_VALUE_ST,// 3
	KEY_VALUE_TIME_MUTE,// 4
	KEY_VALUE_POWER_MODE,// 5
	KEY_VALUE_MODE,
	KEY_VALUE_MUTE,
	KEY_VALUE_SEL,
	KEY_VALUE_ADD,
	KEY_VALUE_TIME,// 10
	KEY_VALUE_POWER_MUTE,
	KEY_VALUE_SUB,
	KEY_VALUE_NAVI_DOWN,
/*---------------------------------------------*/
	KEY_VALUE_M1,
	KEY_VALUE_M2,// 15
	KEY_VALUE_M3,
	KEY_VALUE_M4,
	KEY_VALUE_M5,
	KEY_VALUE_M6,
	KEY_VALUE_NEXT,// 20
	KEY_VALUE_PREV,
	KEY_VALUE_BAND,
	KEY_VALUE_AMS,
	KEY_VALUE_BAND_AMS,
	KEY_VALUE_LOC,
	KEY_VALUE_NAVI_UP,//26
#if defined(_FY700B_PARTY_CONTROL_)
	KEY_VALUE_MODE1,							// 27
	KEY_VALUE_MUTE1,							// 28
	KEY_VALUE_NEXT1,							// 30
	KEY_VALUE_PREV1,							// 31
	KEY_VALUE_ADD1, 						// 32
	KEY_VALUE_SUB1, 							// 33
	KEY_VALUE_BAND1,							// 34
	KEY_VALUE_BAND_AMS1, 					// 37
	KEY_VALUE_NAVI_UP1, 					// 39
	KEY_VALUE_NAVI_DOWN1,					// 40
#endif
/*---------------------------------------------*/
	KEY_VALUE_SCAN,
	KEY_VALUE_LOUD,
	KEY_VALUE_EQ,
	KEY_VALUE_END,	// 30	
};

#define KEY_NAVI_UP				KEY_VALUE_NAVI_UP
#define KEY_NAVI_DOWN			KEY_VALUE_NAVI_DOWN

#define KEY_POWER_MODE			KEY_VALUE_POWER_MODE
#define KEY_POWER_MUTE		    KEY_VALUE_POWER_MUTE

#define KEY_TIME_MUTE		    KEY_VALUE_TIME_MUTE

#endif /* _KEY_MAP_DEMO_H_ */

