#ifndef __DISC_ORDER_H__
#define __DISC_ORDER_H__

#include "easyway_config.h"
#include "typedef.h"


#if defined(_SUPPORT_DISC_)


typedef enum{
	SERVO_ORDER_NULL = 0,										//	0
	SERVO_ORDER_PLAY,
	SERVO_ORDER_PAUSE,
	SERVO_ORDER_STOP,
	SERVO_ORDER_PLAY_PAUSE,

	SERVO_ORDER_PRT,
	SERVO_ORDER_RDM,
	SERVO_ORDER_INT,

	SERVO_ORDER_NEXT,
	SERVO_ORDER_PRVE,
	SERVO_ORDER_FORWARD,										//	10
	SERVO_ORDER_BACKWARD,

	SERVO_ORDER_ESP,
	SERVO_ORDER_SCH,
	SERVO_ORDER_SHOW,
	
	SERVO_ORDER_0,
	SERVO_ORDER_1,
	SERVO_ORDER_2,
	SERVO_ORDER_3,
	SERVO_ORDER_4,
	SERVO_ORDER_5, 												//	20
	SERVO_ORDER_6,
	SERVO_ORDER_7,
	SERVO_ORDER_8,
	SERVO_ORDER_9,
	SERVO_ORDER_10,
	SERVO_ORDER_ADD_10,
	SERVO_ORDER_SUB_10,
	SERVO_ORDER_ADD_DIR,
	SERVO_ORDER_SUB_DIR,
	SERVO_ORDER_TOP,											//	30

	SERVO_ORDER_ADD,
	SERVO_ORDER_SUB,
	SERVO_ORDER_SEL,
	
	SERVO_ORDER_UP,
	SERVO_ORDER_DOWN,
	SERVO_ORDER_LEFT,
	SERVO_ORDER_RIGHT,
	SERVO_ORDER_ENTER,
	SERVO_ORDER_RETURN,
	SERVO_ORDER_DELETE,											//	40

	SERVO_ORDER_DISC,
	SERVO_ORDER_USB,
	SERVO_ORDER_SD,

	SERVO_ORDER_DISC_RESUME,
	SERVO_ORDER_USB_RESUME,
	SERVO_ORDER_SD_RESUME,

	SERVO_ORDER_EJECT,
	SERVO_ORDER_POWER,

	SERVO_ORDER_CHANNEL,		//	左右声道切换	AUDIO 功能 复用
	SERVO_ORDER_OSD,			//	显示OSD	   				//	50
	SERVO_ORDER_PBC,			//	VCD碟片菜单功能	
	SERVO_ORDER_GOTO,			//	碟片跳时功能
	SERVO_ORDER_ZOOM,			//	图像放大缩小功能
	SERVO_ORDER_FORMAT,			//	图像PAL/NTSC制式切换功能
	SERVO_ORDER_SUBP_COPY,		//	字幕、COPY复用功能
	SERVO_ORDER_SETUP,			//	SETUP功能
	SERVO_ORDER_SLOW,			//	慢放功能
	SERVO_ORDER_PROGRAM,		//	编程播放功能
	SERVO_ORDER_ANGLE,			//	角度
	SERVO_ORDER_TITLE,			//	标题   					//	60
	SERVO_ORDER_JPG, 			//	一键转图片
	SERVO_ORDER_MP3MP4, 		//	一键转转MP3/MP4
	SERVO_ORDER_MP3JPEGMP4,		//	一键转播放模式转换

	SERVO_ORDER_AB,
	SERVO_ORDER_COPY,
	SERVO_ORDER_SYNC_DISC,
	SERVO_ORDER_SYNC_USB,
	SERVO_ORDER_SYNC_SD,
	SERVO_ORDER_VERSION,
	SERVO_ORDER_UPGREAD,										//	70
	SERVO_ORDER_FILELIST,
	SERVO_ORDER_TOUCH,
	SERVO_ORDER_GOTOTIME,
	SERVO_ORDER_APPLE,
	SERVO_ORDER_CAR_LOGO,
	SERVO_ORDER_CAR_LANGUAGE,
	SERVO_ORDER_ROOT_MENU,
	SERVO_ORDER_CAR_LOGO_SET,
	SERVO_ORDER_VEDIO_SWITCH,
	
	SERVO_CONTROL_NULL = 0x80,
	SERVO_CONTROL_ID3,
	SERVO_CONTROL_SEARCH,

	SERVO_DISP_NULL = 0xA0,
	SERVO_DISP_VOL,
	SERVO_DISP_BASS,
	SERVO_DISP_TREBLE,
	SERVO_DISP_BAL,
	SERVO_DISP_FAD,
	SERVO_DISP_EQ,
	SERVO_DISP_LOUD,
	SERVO_DISP_MUTE,
	SERVO_DISP_DBAS,
	SERVO_DISP_MBP,
	SERVO_DISP_MEDIA,	
	SERVO_DISP_USER_VFDTYPE,
	SERVO_DISP_INT_RPT_RDM,
	
	SERVO_UPGREAD_ID = 0xF0,
	SERVO_DISP_VERSION = 0xF1,
	SERVO_DISP_LOGO_FLAG = 0xF5,

	SERVO_ORDER_END,
}SERVO_ORDER_e;


extern uint8 DecodeData(uint8 *, uint8);
extern uint8 EncodeData(uint8 *, uint8);
extern uint8 disc_order_send_data(SERVO_ORDER_e, const uint8 *, uint8);
extern uint8 disc_order_send(SERVO_ORDER_e);

extern void disc_audio_init(void);
extern void disc_audio_exit(void);


#endif


#endif/*__DISC_H__*/

